In [15]:
# Install openrouteservice for first time users
# !pip install openrouteservice

In [16]:
import openrouteservice
import pandas as pd
import numpy as np
from tqdm import tqdm

In [17]:
# Load in rental data
rental = pd.read_csv("rea_data/domain/Data/vic_rentals_all_cleaned.csv")
rental_coords = rental[["listing_id", "lon","lat"]]
rental_coords.head()

   listing_id        lon        lat
0    16782629  144.87091 -37.830982
1    17471867  144.86755 -37.826218
2    17721851  144.86632 -37.831226
3    17725855  144.86768 -37.827423
4    17745057  144.86790 -37.826270

In [18]:
# Load in school data
school = pd.read_csv("data\dv402-SchoolLocations2025.csv")
school_coords = school[["School_No", "X","Y"]]
school_coords.head()

   School_No           X          Y
0         20  145.066978 -37.690178
1         25  144.952883 -37.805971
2         26  144.997001 -37.859365
3         28  143.831558 -37.559711
4         29  143.847147 -37.564397

In [19]:
# Define Haversine distance function
def haversine_vec(lon1, lat1, lon2, lat2):
    """
    Compute distance (meters) between two points using vectorised Haversine formula
    """
    lon1_rad = np.radians(lon1)[:, np.newaxis]
    lat1_rad = np.radians(lat1)[:, np.newaxis]

    lon2_rad = np.radians(lon2)[np.newaxis, :]
    lat2_rad = np.radians(lat2)[np.newaxis, :]

    earth_mean_radius = 6371000
    phi1, phi2 = lat1_rad, lat2_rad
    dphi1 = lat2_rad - lat1_rad
    dlambda = lon2_rad - lon1_rad
    
    a = np.sin(dphi1/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))

    return earth_mean_radius * c

In [20]:
# Find top 5 closest schools for each rental
dist_matrix = haversine_vec(rental_coords["lon"].values, rental_coords["lat"].values, school_coords["X"].values, school_coords["Y"].values)

top5_indices = np.argsort(dist_matrix, axis=1)[:,:5]

rental_coords["top5_idx"] = list(top5_indices)
rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

C:\Users\chinj\AppData\Local\Temp\ipykernel_1880\4010516909.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_idx"] = list(top5_indices)
C:\Users\chinj\AppData\Local\Temp\ipykernel_1880\4010516909.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

In [21]:
# Group results by their top 5 closest schools
groups = rental_coords.groupby("top5_tuple")["listing_id"].apply(list).reset_index()
groups["num_rentals"] = groups["listing_id"].apply(len)

In [22]:
# API key for OpenRouteService (ORS); hidden here for privacy
API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImEyMGE4NjZkNjYyZDQ4NDdiN2I4ODJhOWQ1ODM0YThhIiwiaCI6Im11cm11cjY0In0=" # Replace NA with your actual key when running

# Initialize ORS client with the API key
client = openrouteservice.Client(key = API_KEY)

In [23]:
# Batch rentals to stay under API route limit
top_n_schools = 5
max_route_per_batch = 3500

batches = []
current_batch = []
current_batch_rentals = 0

# Loop over each group of rentals that share the same top 5 schools
for _, row in groups.iterrows():
    group_name = row["top5_tuple"]
    rentals = row["listing_id"]
    group_size = len(rentals)

    start = 0
    # Split group into chunks so that adding them won't exceed ORS route limit
    while start < group_size:
        # Estimate number of rentals allowed to add to current batch without exceeding ORS route limit
        num_groups_if_added = len(current_batch) + 1
        max_rentals_for_this_chunk = max(
            (max_route_per_batch // (num_groups_if_added * top_n_schools)) - current_batch_rentals,
            1
        )

        # Determine slice of rentals for this chunk
        end = min(start + max_rentals_for_this_chunk, group_size)
        chunk = rentals[start:end]

        # Compute estimated number of routes if this chunk is added
        num_origins = current_batch_rentals + len(chunk)
        num_destinations = num_groups_if_added * top_n_schools
        estimated_routes = num_origins * num_destinations

        # Start new batch if adding this chunk exceeds ORS route limit
        if estimated_routes >= max_route_per_batch: 
            if current_batch:
                batches.append(current_batch)
            current_batch = [(group_name, chunk)]     
            current_batch_rentals = len(chunk)
        else:
            # Add chunk to batch otherwise
            current_batch.append((group_name, chunk))
            current_batch_rentals += len(chunk)
        start = end

# Append last batch if there are any remaining rentals
if current_batch:
        batches.append(current_batch)

print(f"Created {len(batches)} batches with full ORS route limit logic.")

Created 240 batches with full ORS route limit logic.

In [24]:
# Print and check summary of batches
for i, batch in enumerate(batches):
    num_groups = len(batch)
    num_rentals = sum(len(rentals) for _, rentals in batch)
    print(f"Batch {i+1}: {num_groups} groups, {num_rentals} rentals")

Batch 1: 16 groups, 42 rentals
Batch 2: 6 groups, 116 rentals
Batch 3: 6 groups, 116 rentals
Batch 4: 6 groups, 116 rentals
Batch 5: 9 groups, 69 rentals
Batch 6: 10 groups, 64 rentals
Batch 7: 17 groups, 41 rentals
Batch 8: 14 groups, 49 rentals
Batch 9: 16 groups, 43 rentals
Batch 10: 8 groups, 83 rentals
Batch 11: 16 groups, 43 rentals
Batch 12: 12 groups, 58 rentals
Batch 13: 17 groups, 39 rentals
Batch 14: 15 groups, 44 rentals
Batch 15: 13 groups, 49 rentals
Batch 16: 18 groups, 38 rentals
Batch 17: 16 groups, 41 rentals
Batch 18: 16 groups, 43 rentals
Batch 19: 10 groups, 64 rentals
Batch 20: 12 groups, 58 rentals
Batch 21: 17 groups, 41 rentals
Batch 22: 12 groups, 57 rentals
Batch 23: 18 groups, 36 rentals
Batch 24: 19 groups, 36 rentals
Batch 25: 20 groups, 34 rentals
Batch 26: 16 groups, 43 rentals
Batch 27: 15 groups, 43 rentals
Batch 28: 12 groups, 57 rentals
Batch 29: 9 groups, 70 rentals
Batch 30: 14 groups, 46 rentals
Batch 31: 19 groups, 36 rentals
Batch 32: 12 groups, 53 rentals
Batch 33: 12 groups, 58 rentals
Batch 34: 13 groups, 52 rentals
Batch 35: 6 groups, 111 rentals
Batch 36: 13 groups, 50 rentals
Batch 37: 17 groups, 38 rentals
Batch 38: 17 groups, 38 rentals
Batch 39: 11 groups, 59 rentals
Batch 40: 16 groups, 43 rentals
Batch 41: 17 groups, 41 rentals
Batch 42: 18 groups, 36 rentals
Batch 43: 15 groups, 46 rentals
Batch 44: 18 groups, 37 rentals
Batch 45: 19 groups, 36 rentals
Batch 46: 17 groups, 40 rentals
Batch 47: 18 groups, 36 rentals
Batch 48: 17 groups, 40 rentals
Batch 49: 13 groups, 49 rentals
Batch 50: 16 groups, 42 rentals
Batch 51: 15 groups, 43 rentals
Batch 52: 19 groups, 31 rentals
Batch 53: 12 groups, 56 rentals
Batch 54: 11 groups, 63 rentals
Batch 55: 15 groups, 43 rentals
Batch 56: 11 groups, 58 rentals
Batch 57: 14 groups, 47 rentals
Batch 58: 15 groups, 44 rentals
Batch 59: 13 groups, 50 rentals
Batch 60: 12 groups, 55 rentals
Batch 61: 15 groups, 46 rentals
Batch 62: 13 groups, 53 rentals
Batch 63: 12 groups, 58 rentals
Batch 64: 13 groups, 53 rentals
Batch 65: 18 groups, 37 rentals
Batch 66: 16 groups, 43 rentals
Batch 67: 15 groups, 46 rentals
Batch 68: 13 groups, 53 rentals
Batch 69: 13 groups, 52 rentals
Batch 70: 18 groups, 37 rentals
Batch 71: 15 groups, 45 rentals
Batch 72: 16 groups, 43 rentals
Batch 73: 18 groups, 36 rentals
Batch 74: 15 groups, 46 rentals
Batch 75: 14 groups, 49 rentals
Batch 76: 15 groups, 46 rentals
Batch 77: 14 groups, 48 rentals
Batch 78: 19 groups, 36 rentals
Batch 79: 18 groups, 36 rentals
Batch 80: 20 groups, 34 rentals
Batch 81: 17 groups, 41 rentals
Batch 82: 18 groups, 38 rentals
Batch 83: 15 groups, 43 rentals
Batch 84: 16 groups, 43 rentals
Batch 85: 18 groups, 37 rentals
Batch 86: 17 groups, 40 rentals
Batch 87: 17 groups, 41 rentals
Batch 88: 17 groups, 38 rentals
Batch 89: 18 groups, 38 rentals
Batch 90: 15 groups, 45 rentals
Batch 91: 17 groups, 38 rentals
Batch 92: 15 groups, 43 rentals
Batch 93: 21 groups, 33 rentals
Batch 94: 17 groups, 40 rentals
Batch 95: 17 groups, 41 rentals
Batch 96: 19 groups, 35 rentals
Batch 97: 17 groups, 40 rentals
Batch 98: 18 groups, 36 rentals
Batch 99: 19 groups, 35 rentals
Batch 100: 19 groups, 29 rentals
Batch 101: 12 groups, 56 rentals
Batch 102: 13 groups, 50 rentals
Batch 103: 19 groups, 36 rentals
Batch 104: 13 groups, 45 rentals
Batch 105: 13 groups, 53 rentals
Batch 106: 7 groups, 87 rentals
Batch 107: 14 groups, 47 rentals
Batch 108: 17 groups, 40 rentals
Batch 109: 14 groups, 46 rentals
Batch 110: 17 groups, 41 rentals
Batch 111: 17 groups, 38 rentals
Batch 112: 16 groups, 42 rentals
Batch 113: 15 groups, 46 rentals
Batch 114: 18 groups, 38 rentals
Batch 115: 17 groups, 39 rentals
Batch 116: 18 groups, 36 rentals
Batch 117: 18 groups, 36 rentals
Batch 118: 17 groups, 38 rentals
Batch 119: 19 groups, 36 rentals
Batch 120: 19 groups, 36 rentals
Batch 121: 19 groups, 35 rentals
Batch 122: 18 groups, 38 rentals
Batch 123: 17 groups, 40 rentals
Batch 124: 15 groups, 45 rentals
Batch 125: 17 groups, 39 rentals
Batch 126: 15 groups, 46 rentals
Batch 127: 17 groups, 41 rentals
Batch 128: 19 groups, 36 rentals
Batch 129: 18 groups, 38 rentals
Batch 130: 19 groups, 36 rentals
Batch 131: 15 groups, 45 rentals
Batch 132: 19 groups, 36 rentals
Batch 133: 16 groups, 41 rentals
Batch 134: 13 groups, 50 rentals
Batch 135: 18 groups, 36 rentals
Batch 136: 13 groups, 53 rentals
Batch 137: 12 groups, 58 rentals
Batch 138: 18 groups, 38 rentals
Batch 139: 16 groups, 41 rentals
Batch 140: 16 groups, 43 rentals
Batch 141: 17 groups, 40 rentals
Batch 142: 14 groups, 49 rentals
Batch 143: 17 groups, 38 rentals
Batch 144: 19 groups, 35 rentals
Batch 145: 21 groups, 31 rentals
Batch 146: 17 groups, 39 rentals
Batch 147: 11 groups, 63 rentals
Batch 148: 17 groups, 40 rentals
Batch 149: 18 groups, 37 rentals
Batch 150: 16 groups, 43 rentals
Batch 151: 17 groups, 41 rentals
Batch 152: 19 groups, 34 rentals
Batch 153: 17 groups, 41 rentals
Batch 154: 16 groups, 43 rentals
Batch 155: 13 groups, 52 rentals
Batch 156: 12 groups, 56 rentals
Batch 157: 15 groups, 44 rentals
Batch 158: 19 groups, 30 rentals
Batch 159: 9 groups, 66 rentals
Batch 160: 17 groups, 41 rentals
Batch 161: 14 groups, 47 rentals
Batch 162: 12 groups, 57 rentals
Batch 163: 16 groups, 43 rentals
Batch 164: 8 groups, 87 rentals
Batch 165: 13 groups, 48 rentals
Batch 166: 15 groups, 46 rentals
Batch 167: 15 groups, 45 rentals
Batch 168: 19 groups, 36 rentals
Batch 169: 17 groups, 38 rentals
Batch 170: 11 groups, 60 rentals
Batch 171: 9 groups, 44 rentals
Batch 172: 12 groups, 56 rentals
Batch 173: 13 groups, 52 rentals
Batch 174: 9 groups, 75 rentals
Batch 175: 12 groups, 58 rentals
Batch 176: 14 groups, 47 rentals
Batch 177: 15 groups, 46 rentals
Batch 178: 9 groups, 72 rentals
Batch 179: 8 groups, 87 rentals
Batch 180: 12 groups, 56 rentals
Batch 181: 15 groups, 46 rentals
Batch 182: 15 groups, 46 rentals
Batch 183: 11 groups, 63 rentals
Batch 184: 9 groups, 60 rentals
Batch 185: 12 groups, 58 rentals
Batch 186: 10 groups, 68 rentals
Batch 187: 13 groups, 40 rentals
Batch 188: 11 groups, 60 rentals
Batch 189: 8 groups, 87 rentals
Batch 190: 11 groups, 63 rentals
Batch 191: 13 groups, 49 rentals
Batch 192: 8 groups, 85 rentals
Batch 193: 15 groups, 44 rentals
Batch 194: 11 groups, 63 rentals
Batch 195: 8 groups, 84 rentals
Batch 196: 11 groups, 63 rentals
Batch 197: 9 groups, 77 rentals
Batch 198: 14 groups, 48 rentals
Batch 199: 13 groups, 53 rentals
Batch 200: 16 groups, 43 rentals
Batch 201: 18 groups, 37 rentals
Batch 202: 9 groups, 39 rentals
Batch 203: 5 groups, 117 rentals
Batch 204: 14 groups, 49 rentals
Batch 205: 17 groups, 41 rentals
Batch 206: 7 groups, 91 rentals
Batch 207: 19 groups, 36 rentals
Batch 208: 15 groups, 46 rentals
Batch 209: 15 groups, 46 rentals
Batch 210: 20 groups, 33 rentals
Batch 211: 8 groups, 79 rentals
Batch 212: 14 groups, 48 rentals
Batch 213: 13 groups, 49 rentals
Batch 214: 13 groups, 47 rentals
Batch 215: 17 groups, 39 rentals
Batch 216: 13 groups, 50 rentals
Batch 217: 13 groups, 45 rentals
Batch 218: 6 groups, 83 rentals
Batch 219: 6 groups, 107 rentals
Batch 220: 17 groups, 40 rentals
Batch 221: 17 groups, 38 rentals
Batch 222: 15 groups, 44 rentals
Batch 223: 18 groups, 36 rentals
Batch 224: 21 groups, 33 rentals
Batch 225: 16 groups, 41 rentals
Batch 226: 16 groups, 43 rentals
Batch 227: 21 groups, 33 rentals
Batch 228: 20 groups, 34 rentals
Batch 229: 20 groups, 33 rentals
Batch 230: 17 groups, 38 rentals
Batch 231: 19 groups, 30 rentals
Batch 232: 18 groups, 38 rentals
Batch 233: 21 groups, 33 rentals
Batch 234: 16 groups, 43 rentals
Batch 235: 16 groups, 43 rentals
Batch 236: 14 groups, 46 rentals
Batch 237: 9 groups, 71 rentals
Batch 238: 11 groups, 63 rentals
Batch 239: 9 groups, 75 rentals
Batch 240: 7 groups, 16 rentals

In [53]:
# Call ORS to get distance to closest schools
all_rental_ids = []
all_distances = []
all_school_ids = []

for batch in tqdm(batches, desc="Processing batches"):
    batch_rentals = [r for _, rentals in batch for r in rentals]
    batch_coords = rental_coords.set_index("listing_id").loc[batch_rentals][["lon", "lat"]].values.tolist()

    batch_school_indices = [
        rental_coords.loc[rental_coords["listing_id"]==r, "top5_idx"].values[0] for r in batch_rentals
    ]

    unique_school_indices = list(set(idx for indices in batch_school_indices for idx in indices))

    origins = batch_coords
    destinations = school_coords.loc[school_coords.index.isin(unique_school_indices)][["X", "Y"]].values.tolist()
    dest_ids_map = {idx: school_coords["School_No"].iloc[idx] for idx in unique_school_indices}
   
    school_pos_map = {idx: i for i, idx in enumerate(unique_school_indices)}

    num_origins = len(origins)
    num_destinations = len(destinations)
    num_routes = num_origins * num_destinations
    print(f"Checking batch → {num_origins} origins × {num_destinations} destinations = {num_routes} routes")

    # Call ORS distance matrix
    matrix = client.distance_matrix(
        locations = origins + destinations,
        profile = "driving-car",
        metrics = ["distance"],
        sources = list(range(len(origins))),
        destinations = list(range(len(origins), len(origins)+len(destinations)))
    )

    # Extract distances and school IDs for top 5 schools
    for i, rental in enumerate(batch_rentals):
        top_indices = batch_school_indices[i]
        dest_positions = [school_pos_map[idx] for idx in top_indices]
        rental_distances = [matrix["distances"][i][pos] for pos in dest_positions]
        rental_school_ids = [dest_ids_map[idx] for idx in top_indices]

        sorted_idx = np.argsort(rental_distances)
        top_n_distances = [rental_distances[k] for k in sorted_idx]
        top_n_ids = [rental_school_ids[k] for k in sorted_idx]

        all_rental_ids.append(batch_rentals[i])
        all_distances.append(top_n_distances)
        all_school_ids.append(top_n_ids)

Processing batches:   0%|          | 0/240 [00:00<?, ?it/s]

Checking batch → 42 origins × 25 destinations = 1050 routes

Processing batches:   0%|          | 1/240 [00:03<12:24,  3.12s/it]

Checking batch → 116 origins × 8 destinations = 928 routes

Processing batches:   1%|          | 2/240 [00:03<06:01,  1.52s/it]

Checking batch → 116 origins × 9 destinations = 1044 routes

Processing batches:   1%|▏         | 3/240 [00:03<03:57,  1.00s/it]

Checking batch → 116 origins × 9 destinations = 1044 routes

Processing batches:   2%|▏         | 4/240 [00:04<03:01,  1.30it/s]

Checking batch → 69 origins × 18 destinations = 1242 routes

Processing batches:   2%|▏         | 5/240 [00:04<02:29,  1.57it/s]

Checking batch → 64 origins × 12 destinations = 768 routes

Processing batches:   2%|▎         | 6/240 [00:05<02:07,  1.84it/s]

Checking batch → 41 origins × 30 destinations = 1230 routes

Processing batches:   3%|▎         | 7/240 [00:05<01:54,  2.03it/s]

Checking batch → 49 origins × 24 destinations = 1176 routes

Processing batches:   3%|▎         | 8/240 [00:05<01:46,  2.18it/s]

Checking batch → 43 origins × 28 destinations = 1204 routes

Processing batches:   4%|▍         | 9/240 [00:06<01:41,  2.26it/s]

Checking batch → 83 origins × 16 destinations = 1328 routes

Processing batches:   4%|▍         | 10/240 [00:06<01:38,  2.33it/s]

Checking batch → 43 origins × 39 destinations = 1677 routes

Processing batches:   5%|▍         | 11/240 [00:07<01:38,  2.33it/s]

Checking batch → 58 origins × 13 destinations = 754 routes

Processing batches:   5%|▌         | 12/240 [00:07<01:33,  2.43it/s]

Checking batch → 39 origins × 19 destinations = 741 routes

Processing batches:   5%|▌         | 13/240 [00:07<01:30,  2.52it/s]

Checking batch → 44 origins × 30 destinations = 1320 routes

Processing batches:   6%|▌         | 14/240 [00:08<01:29,  2.54it/s]

Checking batch → 49 origins × 21 destinations = 1029 routes

Processing batches:   6%|▋         | 15/240 [00:08<01:27,  2.57it/s]

Checking batch → 38 origins × 29 destinations = 1102 routes

Processing batches:   7%|▋         | 16/240 [00:09<01:28,  2.52it/s]

Checking batch → 41 origins × 22 destinations = 902 routes

Processing batches:   7%|▋         | 17/240 [00:09<01:27,  2.55it/s]

Checking batch → 43 origins × 18 destinations = 774 routes

Processing batches:   8%|▊         | 18/240 [00:09<01:25,  2.59it/s]

Checking batch → 64 origins × 18 destinations = 1152 routes

Processing batches:   8%|▊         | 19/240 [00:10<01:24,  2.61it/s]

Checking batch → 58 origins × 17 destinations = 986 routes

Processing batches:   8%|▊         | 20/240 [00:10<01:24,  2.61it/s]

Checking batch → 41 origins × 57 destinations = 2337 routes

Processing batches:   9%|▉         | 21/240 [00:10<01:25,  2.56it/s]

Checking batch → 57 origins × 26 destinations = 1482 routes

Processing batches:   9%|▉         | 22/240 [00:11<01:25,  2.54it/s]

Checking batch → 36 origins × 31 destinations = 1116 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  10%|▉         | 23/240 [00:19<10:24,  2.88s/it]

Checking batch → 36 origins × 37 destinations = 1332 routes

Processing batches:  10%|█         | 24/240 [00:20<07:42,  2.14s/it]

Checking batch → 34 origins × 43 destinations = 1462 routes

Processing batches:  10%|█         | 25/240 [00:20<05:46,  1.61s/it]

Checking batch → 43 origins × 32 destinations = 1376 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  11%|█         | 26/240 [00:22<05:43,  1.60s/it]

Checking batch → 43 origins × 12 destinations = 516 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  11%|█▏        | 27/240 [01:09<54:14, 15.28s/it]

Checking batch → 57 origins × 19 destinations = 1083 routes

Processing batches:  12%|█▏        | 28/240 [01:09<38:11, 10.81s/it]

Checking batch → 70 origins × 14 destinations = 980 routes

Processing batches:  12%|█▏        | 29/240 [01:10<27:01,  7.68s/it]

Checking batch → 46 origins × 27 destinations = 1242 routes

Processing batches:  12%|█▎        | 30/240 [01:10<19:15,  5.50s/it]

Checking batch → 36 origins × 45 destinations = 1620 routes

Processing batches:  13%|█▎        | 31/240 [01:11<13:50,  3.97s/it]

Checking batch → 53 origins × 13 destinations = 689 routes

Processing batches:  13%|█▎        | 32/240 [01:11<10:02,  2.90s/it]

Checking batch → 58 origins × 20 destinations = 1160 routes

Processing batches:  14%|█▍        | 33/240 [01:11<07:24,  2.15s/it]

Checking batch → 52 origins × 28 destinations = 1456 routes

Processing batches:  14%|█▍        | 34/240 [01:12<05:34,  1.63s/it]

Checking batch → 111 origins × 10 destinations = 1110 routes

Processing batches:  15%|█▍        | 35/240 [01:12<04:17,  1.26s/it]

Checking batch → 50 origins × 19 destinations = 950 routes

Processing batches:  15%|█▌        | 36/240 [01:13<03:23,  1.00it/s]

Checking batch → 38 origins × 27 destinations = 1026 routes

Processing batches:  15%|█▌        | 37/240 [01:13<02:44,  1.23it/s]

Checking batch → 38 origins × 36 destinations = 1368 routes

Processing batches:  16%|█▌        | 38/240 [01:13<02:19,  1.45it/s]

Checking batch → 59 origins × 24 destinations = 1416 routes

Processing batches:  16%|█▋        | 39/240 [01:14<02:00,  1.67it/s]

Checking batch → 43 origins × 20 destinations = 860 routes

Processing batches:  17%|█▋        | 40/240 [01:14<01:46,  1.88it/s]

Checking batch → 41 origins × 16 destinations = 656 routes

Processing batches:  17%|█▋        | 41/240 [01:15<01:35,  2.08it/s]

Checking batch → 36 origins × 33 destinations = 1188 routes

Processing batches:  18%|█▊        | 42/240 [01:15<01:30,  2.19it/s]

Checking batch → 46 origins × 26 destinations = 1196 routes

Processing batches:  18%|█▊        | 43/240 [01:15<01:26,  2.28it/s]

Checking batch → 37 origins × 44 destinations = 1628 routes

Processing batches:  18%|█▊        | 44/240 [01:16<01:25,  2.29it/s]

Checking batch → 36 origins × 36 destinations = 1296 routes

Processing batches:  19%|█▉        | 45/240 [01:16<01:24,  2.30it/s]

Checking batch → 40 origins × 38 destinations = 1520 routes

Processing batches:  19%|█▉        | 46/240 [01:17<01:22,  2.36it/s]

Checking batch → 36 origins × 44 destinations = 1584 routes

Processing batches:  20%|█▉        | 47/240 [01:17<01:20,  2.38it/s]

Checking batch → 40 origins × 29 destinations = 1160 routes

Processing batches:  20%|██        | 48/240 [01:17<01:18,  2.46it/s]

Checking batch → 49 origins × 22 destinations = 1078 routes

Processing batches:  20%|██        | 49/240 [01:18<01:16,  2.50it/s]

Checking batch → 42 origins × 25 destinations = 1050 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  21%|██        | 50/240 [01:33<15:32,  4.91s/it]

Checking batch → 43 origins × 14 destinations = 602 routes

Processing batches:  21%|██▏       | 51/240 [01:34<11:09,  3.54s/it]

Checking batch → 31 origins × 33 destinations = 1023 routes

Processing batches:  22%|██▏       | 52/240 [01:34<08:08,  2.60s/it]

Checking batch → 56 origins × 11 destinations = 616 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  22%|██▏       | 53/240 [02:22<50:11, 16.11s/it]

Checking batch → 63 origins × 13 destinations = 819 routes

Processing batches:  22%|██▎       | 54/240 [02:22<35:18, 11.39s/it]

Checking batch → 43 origins × 23 destinations = 989 routes

Processing batches:  23%|██▎       | 55/240 [02:22<24:56,  8.09s/it]

Checking batch → 58 origins × 20 destinations = 1160 routes

Processing batches:  23%|██▎       | 56/240 [02:23<17:42,  5.77s/it]

Checking batch → 47 origins × 31 destinations = 1457 routes

Processing batches:  24%|██▍       | 57/240 [02:23<12:42,  4.17s/it]

Checking batch → 44 origins × 27 destinations = 1188 routes

Processing batches:  24%|██▍       | 58/240 [02:24<09:12,  3.04s/it]

Checking batch → 50 origins × 22 destinations = 1100 routes

Processing batches:  25%|██▍       | 59/240 [02:24<06:45,  2.24s/it]

Checking batch → 55 origins × 26 destinations = 1430 routes

Processing batches:  25%|██▌       | 60/240 [02:24<05:04,  1.69s/it]

Checking batch → 46 origins × 40 destinations = 1840 routes

Processing batches:  25%|██▌       | 61/240 [02:25<03:54,  1.31s/it]

Checking batch → 53 origins × 26 destinations = 1378 routes

Processing batches:  26%|██▌       | 62/240 [02:25<03:04,  1.03s/it]

Checking batch → 58 origins × 29 destinations = 1682 routes

Processing batches:  26%|██▋       | 63/240 [02:26<02:30,  1.17it/s]

Checking batch → 53 origins × 25 destinations = 1325 routes

Processing batches:  27%|██▋       | 64/240 [02:26<02:05,  1.40it/s]

Checking batch → 37 origins × 27 destinations = 999 routes

Processing batches:  27%|██▋       | 65/240 [02:26<01:53,  1.55it/s]

Checking batch → 43 origins × 29 destinations = 1247 routes

Processing batches:  28%|██▊       | 66/240 [02:27<01:38,  1.76it/s]

Checking batch → 46 origins × 21 destinations = 966 routes

Processing batches:  28%|██▊       | 67/240 [02:27<01:28,  1.95it/s]

Checking batch → 53 origins × 24 destinations = 1272 routes

Processing batches:  28%|██▊       | 68/240 [02:28<01:21,  2.10it/s]

Checking batch → 52 origins × 22 destinations = 1144 routes

Processing batches:  29%|██▉       | 69/240 [02:28<01:17,  2.21it/s]

Checking batch → 37 origins × 39 destinations = 1443 routes

Processing batches:  29%|██▉       | 70/240 [02:28<01:16,  2.23it/s]

Checking batch → 45 origins × 32 destinations = 1440 routes

Processing batches:  30%|██▉       | 71/240 [02:29<01:14,  2.27it/s]

Checking batch → 43 origins × 30 destinations = 1290 routes

Processing batches:  30%|███       | 72/240 [02:29<01:12,  2.33it/s]

Checking batch → 36 origins × 24 destinations = 864 routes

Processing batches:  30%|███       | 73/240 [02:30<01:09,  2.41it/s]

Checking batch → 46 origins × 33 destinations = 1518 routes

Processing batches:  31%|███       | 74/240 [02:30<01:11,  2.32it/s]

Checking batch → 49 origins × 15 destinations = 735 routes

Processing batches:  31%|███▏      | 75/240 [02:30<01:08,  2.42it/s]

Checking batch → 46 origins × 29 destinations = 1334 routes

Processing batches:  32%|███▏      | 76/240 [02:31<01:07,  2.44it/s]

Checking batch → 48 origins × 27 destinations = 1296 routes

Processing batches:  32%|███▏      | 77/240 [02:31<01:06,  2.46it/s]

Checking batch → 36 origins × 26 destinations = 936 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  32%|███▎      | 78/240 [02:34<02:37,  1.03it/s]

Checking batch → 36 origins × 25 destinations = 900 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  33%|███▎      | 79/240 [03:35<51:20, 19.13s/it]

Checking batch → 34 origins × 39 destinations = 1326 routes

Processing batches:  33%|███▎      | 80/240 [03:35<36:02, 13.51s/it]

Checking batch → 41 origins × 30 destinations = 1230 routes

Processing batches:  34%|███▍      | 81/240 [03:36<25:23,  9.58s/it]

Checking batch → 38 origins × 31 destinations = 1178 routes

Processing batches:  34%|███▍      | 82/240 [03:36<17:59,  6.83s/it]

Checking batch → 43 origins × 36 destinations = 1548 routes

Processing batches:  35%|███▍      | 83/240 [03:37<12:50,  4.91s/it]

Checking batch → 43 origins × 29 destinations = 1247 routes

Processing batches:  35%|███▌      | 84/240 [03:37<09:14,  3.55s/it]

Checking batch → 37 origins × 23 destinations = 851 routes

Processing batches:  35%|███▌      | 85/240 [03:38<06:43,  2.60s/it]

Checking batch → 40 origins × 35 destinations = 1400 routes

Processing batches:  36%|███▌      | 86/240 [03:38<04:59,  1.94s/it]

Checking batch → 41 origins × 22 destinations = 902 routes

Processing batches:  36%|███▋      | 87/240 [03:38<03:45,  1.47s/it]

Checking batch → 38 origins × 38 destinations = 1444 routes

Processing batches:  37%|███▋      | 88/240 [03:39<02:55,  1.16s/it]

Checking batch → 38 origins × 44 destinations = 1672 routes

Processing batches:  37%|███▋      | 89/240 [03:39<02:21,  1.07it/s]

Checking batch → 45 origins × 27 destinations = 1215 routes

Processing batches:  38%|███▊      | 90/240 [03:40<01:56,  1.29it/s]

Checking batch → 38 origins × 29 destinations = 1102 routes

Processing batches:  38%|███▊      | 91/240 [03:40<01:38,  1.51it/s]

Checking batch → 43 origins × 33 destinations = 1419 routes

Processing batches:  38%|███▊      | 92/240 [03:40<01:27,  1.70it/s]

Checking batch → 33 origins × 37 destinations = 1221 routes

Processing batches:  39%|███▉      | 93/240 [03:41<01:19,  1.84it/s]

Checking batch → 40 origins × 34 destinations = 1360 routes

Processing batches:  39%|███▉      | 94/240 [03:41<01:14,  1.95it/s]

Checking batch → 41 origins × 39 destinations = 1599 routes

Processing batches:  40%|███▉      | 95/240 [03:42<01:10,  2.05it/s]

Checking batch → 35 origins × 41 destinations = 1435 routes

Processing batches:  40%|████      | 96/240 [03:42<01:07,  2.12it/s]

Checking batch → 40 origins × 22 destinations = 880 routes

Processing batches:  40%|████      | 97/240 [03:42<01:03,  2.26it/s]

Checking batch → 36 origins × 37 destinations = 1332 routes

Processing batches:  41%|████      | 98/240 [03:43<01:01,  2.29it/s]

Checking batch → 35 origins × 26 destinations = 910 routes

Processing batches:  41%|████▏     | 99/240 [03:43<00:59,  2.35it/s]

Checking batch → 29 origins × 37 destinations = 1073 routes

Processing batches:  42%|████▏     | 100/240 [03:44<00:59,  2.37it/s]

Checking batch → 56 origins × 17 destinations = 952 routes

Processing batches:  42%|████▏     | 101/240 [03:44<00:56,  2.45it/s]

Checking batch → 50 origins × 21 destinations = 1050 routes

Processing batches:  42%|████▎     | 102/240 [03:44<00:55,  2.47it/s]

Checking batch → 36 origins × 31 destinations = 1116 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  43%|████▎     | 103/240 [03:49<03:47,  1.66s/it]

Checking batch → 45 origins × 24 destinations = 1080 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  43%|████▎     | 104/240 [03:51<04:09,  1.83s/it]

Checking batch → 53 origins × 12 destinations = 636 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  44%|████▍     | 105/240 [04:46<39:48, 17.69s/it]

Checking batch → 87 origins × 11 destinations = 957 routes

Processing batches:  44%|████▍     | 106/240 [04:47<28:18, 12.68s/it]

Checking batch → 47 origins × 31 destinations = 1457 routes

Processing batches:  45%|████▍     | 107/240 [04:47<19:57,  9.00s/it]

Checking batch → 40 origins × 38 destinations = 1520 routes

Processing batches:  45%|████▌     | 108/240 [04:48<14:07,  6.42s/it]

Checking batch → 46 origins × 21 destinations = 966 routes

Processing batches:  45%|████▌     | 109/240 [04:48<10:03,  4.61s/it]

Checking batch → 41 origins × 20 destinations = 820 routes

Processing batches:  46%|████▌     | 110/240 [04:49<07:13,  3.34s/it]

Checking batch → 38 origins × 45 destinations = 1710 routes

Processing batches:  46%|████▋     | 111/240 [04:49<05:17,  2.46s/it]

Checking batch → 42 origins × 24 destinations = 1008 routes

Processing batches:  47%|████▋     | 112/240 [04:49<03:55,  1.84s/it]

Checking batch → 46 origins × 29 destinations = 1334 routes

Processing batches:  47%|████▋     | 113/240 [04:50<02:58,  1.41s/it]

Checking batch → 38 origins × 23 destinations = 874 routes

Processing batches:  48%|████▊     | 114/240 [04:50<02:18,  1.10s/it]

Checking batch → 39 origins × 38 destinations = 1482 routes

Processing batches:  48%|████▊     | 115/240 [04:51<01:52,  1.11it/s]

Checking batch → 36 origins × 25 destinations = 900 routes

Processing batches:  48%|████▊     | 116/240 [04:51<01:31,  1.36it/s]

Checking batch → 36 origins × 45 destinations = 1620 routes

Processing batches:  49%|████▉     | 117/240 [04:51<01:20,  1.53it/s]

Checking batch → 38 origins × 25 destinations = 950 routes

Processing batches:  49%|████▉     | 118/240 [04:52<01:09,  1.76it/s]

Checking batch → 36 origins × 27 destinations = 972 routes

Processing batches:  50%|████▉     | 119/240 [04:52<01:02,  1.94it/s]

Checking batch → 36 origins × 28 destinations = 1008 routes

Processing batches:  50%|█████     | 120/240 [04:53<00:56,  2.11it/s]

Checking batch → 35 origins × 39 destinations = 1365 routes

Processing batches:  50%|█████     | 121/240 [04:53<00:53,  2.21it/s]

Checking batch → 38 origins × 31 destinations = 1178 routes

Processing batches:  51%|█████     | 122/240 [04:53<00:51,  2.29it/s]

Checking batch → 40 origins × 28 destinations = 1120 routes

Processing batches:  51%|█████▏    | 123/240 [04:54<00:49,  2.36it/s]

Checking batch → 45 origins × 35 destinations = 1575 routes

Processing batches:  52%|█████▏    | 124/240 [04:54<00:48,  2.38it/s]

Checking batch → 39 origins × 42 destinations = 1638 routes

Processing batches:  52%|█████▏    | 125/240 [04:55<00:49,  2.32it/s]

Checking batch → 46 origins × 30 destinations = 1380 routes

Processing batches:  52%|█████▎    | 126/240 [04:55<00:48,  2.37it/s]

Checking batch → 41 origins × 27 destinations = 1107 routes

Processing batches:  53%|█████▎    | 127/240 [04:55<00:47,  2.40it/s]

Checking batch → 36 origins × 36 destinations = 1296 routes

Processing batches:  53%|█████▎    | 128/240 [04:56<00:46,  2.41it/s]

Checking batch → 38 origins × 28 destinations = 1064 routes

Processing batches:  54%|█████▍    | 129/240 [04:56<00:44,  2.48it/s]

Checking batch → 36 origins × 29 destinations = 1044 routes

Processing batches:  54%|█████▍    | 130/240 [04:57<00:44,  2.48it/s]

Checking batch → 45 origins × 37 destinations = 1665 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  55%|█████▍    | 131/240 [05:49<28:49, 15.87s/it]

Checking batch → 36 origins × 28 destinations = 1008 routes

Processing batches:  55%|█████▌    | 132/240 [05:49<20:12, 11.23s/it]

Checking batch → 41 origins × 28 destinations = 1148 routes

Processing batches:  55%|█████▌    | 133/240 [05:49<14:14,  7.98s/it]

Checking batch → 50 origins × 22 destinations = 1100 routes

Processing batches:  56%|█████▌    | 134/240 [05:50<10:05,  5.71s/it]

Checking batch → 36 origins × 37 destinations = 1332 routes

Processing batches:  56%|█████▋    | 135/240 [05:50<07:12,  4.12s/it]

Checking batch → 53 origins × 35 destinations = 1855 routes

Processing batches:  57%|█████▋    | 136/240 [05:51<05:12,  3.00s/it]

Checking batch → 58 origins × 30 destinations = 1740 routes

Processing batches:  57%|█████▋    | 137/240 [05:51<04:03,  2.37s/it]

Checking batch → 38 origins × 43 destinations = 1634 routes

Processing batches:  57%|█████▊    | 138/240 [05:52<03:02,  1.78s/it]

Checking batch → 41 origins × 30 destinations = 1230 routes

Processing batches:  58%|█████▊    | 139/240 [05:52<02:21,  1.40s/it]

Checking batch → 43 origins × 28 destinations = 1204 routes

Processing batches:  58%|█████▊    | 140/240 [05:53<01:54,  1.14s/it]

Checking batch → 40 origins × 30 destinations = 1200 routes

Processing batches:  59%|█████▉    | 141/240 [05:53<01:33,  1.06it/s]

Checking batch → 49 origins × 23 destinations = 1127 routes

Processing batches:  59%|█████▉    | 142/240 [05:54<01:16,  1.28it/s]

Checking batch → 38 origins × 36 destinations = 1368 routes

Processing batches:  60%|█████▉    | 143/240 [05:54<01:04,  1.50it/s]

Checking batch → 35 origins × 38 destinations = 1330 routes

Processing batches:  60%|██████    | 144/240 [05:55<01:00,  1.57it/s]

Checking batch → 31 origins × 40 destinations = 1240 routes

Processing batches:  60%|██████    | 145/240 [05:55<00:53,  1.77it/s]

Checking batch → 39 origins × 29 destinations = 1131 routes

Processing batches:  61%|██████    | 146/240 [05:56<01:01,  1.53it/s]

Checking batch → 63 origins × 22 destinations = 1386 routes

Processing batches:  61%|██████▏   | 147/240 [05:57<01:06,  1.39it/s]

Checking batch → 40 origins × 29 destinations = 1160 routes

Processing batches:  62%|██████▏   | 148/240 [05:58<01:08,  1.34it/s]

Checking batch → 37 origins × 50 destinations = 1850 routes

Processing batches:  62%|██████▏   | 149/240 [05:58<01:00,  1.51it/s]

Checking batch → 43 origins × 24 destinations = 1032 routes

Processing batches:  62%|██████▎   | 150/240 [05:59<00:54,  1.65it/s]

Checking batch → 41 origins × 35 destinations = 1435 routes

Processing batches:  63%|██████▎   | 151/240 [05:59<00:51,  1.74it/s]

Checking batch → 34 origins × 36 destinations = 1224 routes

Processing batches:  63%|██████▎   | 152/240 [06:00<00:46,  1.91it/s]

Checking batch → 41 origins × 29 destinations = 1189 routes

Processing batches:  64%|██████▍   | 153/240 [06:00<00:42,  2.03it/s]

Checking batch → 43 origins × 24 destinations = 1032 routes

Processing batches:  64%|██████▍   | 154/240 [06:00<00:39,  2.16it/s]

Checking batch → 52 origins × 24 destinations = 1248 routes

Processing batches:  65%|██████▍   | 155/240 [06:01<00:37,  2.27it/s]

Checking batch → 56 origins × 38 destinations = 2128 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  65%|██████▌   | 156/240 [06:54<22:49, 16.31s/it]

Checking batch → 44 origins × 40 destinations = 1760 routes

Processing batches:  65%|██████▌   | 157/240 [06:54<15:57, 11.54s/it]

Checking batch → 30 origins × 27 destinations = 810 routes

Processing batches:  66%|██████▌   | 158/240 [06:55<11:12,  8.20s/it]

Checking batch → 66 origins × 14 destinations = 924 routes

Processing batches:  66%|██████▋   | 159/240 [06:55<07:53,  5.85s/it]

Checking batch → 41 origins × 38 destinations = 1558 routes

Processing batches:  67%|██████▋   | 160/240 [06:56<05:37,  4.22s/it]

Checking batch → 47 origins × 22 destinations = 1034 routes

Processing batches:  67%|██████▋   | 161/240 [06:56<04:02,  3.07s/it]

Checking batch → 57 origins × 23 destinations = 1311 routes

Processing batches:  68%|██████▊   | 162/240 [06:56<02:56,  2.26s/it]

Checking batch → 43 origins × 19 destinations = 817 routes

Processing batches:  68%|██████▊   | 163/240 [06:57<02:10,  1.70s/it]

Checking batch → 87 origins × 10 destinations = 870 routes

Processing batches:  68%|██████▊   | 164/240 [06:57<01:39,  1.30s/it]

Checking batch → 48 origins × 28 destinations = 1344 routes

Processing batches:  69%|██████▉   | 165/240 [06:58<01:17,  1.03s/it]

Checking batch → 46 origins × 15 destinations = 690 routes

Processing batches:  69%|██████▉   | 166/240 [06:58<01:01,  1.20it/s]

Checking batch → 45 origins × 34 destinations = 1530 routes

Processing batches:  70%|██████▉   | 167/240 [06:58<00:51,  1.42it/s]

Checking batch → 36 origins × 23 destinations = 828 routes

Processing batches:  70%|███████   | 168/240 [06:59<00:43,  1.65it/s]

Checking batch → 38 origins × 35 destinations = 1330 routes

Processing batches:  70%|███████   | 169/240 [06:59<00:38,  1.85it/s]

Checking batch → 60 origins × 19 destinations = 1140 routes

Processing batches:  71%|███████   | 170/240 [07:00<00:34,  2.03it/s]

Checking batch → 44 origins × 12 destinations = 528 routes

Processing batches:  71%|███████▏  | 171/240 [07:00<00:31,  2.21it/s]

Checking batch → 56 origins × 24 destinations = 1344 routes

Processing batches:  72%|███████▏  | 172/240 [07:00<00:29,  2.28it/s]

Checking batch → 52 origins × 28 destinations = 1456 routes

Processing batches:  72%|███████▏  | 173/240 [07:01<00:28,  2.35it/s]

Checking batch → 75 origins × 15 destinations = 1125 routes

Processing batches:  72%|███████▎  | 174/240 [07:01<00:27,  2.41it/s]

Checking batch → 58 origins × 18 destinations = 1044 routes

Processing batches:  73%|███████▎  | 175/240 [07:01<00:26,  2.45it/s]

Checking batch → 47 origins × 21 destinations = 987 routes

Processing batches:  73%|███████▎  | 176/240 [07:02<00:26,  2.41it/s]

Checking batch → 46 origins × 25 destinations = 1150 routes

Processing batches:  74%|███████▍  | 177/240 [07:02<00:26,  2.36it/s]

Checking batch → 72 origins × 17 destinations = 1224 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  74%|███████▍  | 178/240 [07:05<01:03,  1.03s/it]

Checking batch → 87 origins × 10 destinations = 870 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  75%|███████▍  | 179/240 [07:08<01:42,  1.69s/it]

Checking batch → 56 origins × 18 destinations = 1008 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  75%|███████▌  | 180/240 [07:12<02:16,  2.27s/it]

Checking batch → 46 origins × 35 destinations = 1610 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  75%|███████▌  | 181/240 [07:13<02:06,  2.14s/it]

Checking batch → 46 origins × 26 destinations = 1196 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  76%|███████▌  | 182/240 [07:59<14:32, 15.05s/it]

Checking batch → 63 origins × 19 destinations = 1197 routes

Processing batches:  76%|███████▋  | 183/240 [07:59<10:07, 10.66s/it]

Checking batch → 60 origins × 10 destinations = 600 routes

Processing batches:  77%|███████▋  | 184/240 [07:59<07:03,  7.57s/it]

Checking batch → 58 origins × 18 destinations = 1044 routes

Processing batches:  77%|███████▋  | 185/240 [08:00<04:57,  5.41s/it]

Checking batch → 68 origins × 16 destinations = 1088 routes

Processing batches:  78%|███████▊  | 186/240 [08:00<03:30,  3.91s/it]

Checking batch → 40 origins × 26 destinations = 1040 routes

Processing batches:  78%|███████▊  | 187/240 [08:06<03:53,  4.40s/it]

Checking batch → 60 origins × 15 destinations = 900 routes

Processing batches:  78%|███████▊  | 188/240 [08:06<02:46,  3.19s/it]

Checking batch → 87 origins × 10 destinations = 870 routes

Processing batches:  79%|███████▉  | 189/240 [08:07<02:00,  2.36s/it]

Checking batch → 63 origins × 26 destinations = 1638 routes

Processing batches:  79%|███████▉  | 190/240 [08:07<01:28,  1.77s/it]

Checking batch → 49 origins × 29 destinations = 1421 routes

Processing batches:  80%|███████▉  | 191/240 [08:07<01:06,  1.35s/it]

Checking batch → 85 origins × 16 destinations = 1360 routes

Processing batches:  80%|████████  | 192/240 [08:08<00:50,  1.06s/it]

Checking batch → 44 origins × 25 destinations = 1100 routes

Processing batches:  80%|████████  | 193/240 [08:08<00:40,  1.15it/s]

Checking batch → 63 origins × 20 destinations = 1260 routes

Processing batches:  81%|████████  | 194/240 [08:08<00:33,  1.38it/s]

Checking batch → 84 origins × 19 destinations = 1596 routes

Processing batches:  81%|████████▏ | 195/240 [08:09<00:28,  1.60it/s]

Checking batch → 63 origins × 16 destinations = 1008 routes

Processing batches:  82%|████████▏ | 196/240 [08:09<00:24,  1.77it/s]

Checking batch → 77 origins × 26 destinations = 2002 routes

Processing batches:  82%|████████▏ | 197/240 [08:10<00:22,  1.94it/s]

Checking batch → 48 origins × 35 destinations = 1680 routes

Processing batches:  82%|████████▎ | 198/240 [08:10<00:20,  2.05it/s]

Checking batch → 53 origins × 41 destinations = 2173 routes

Processing batches:  83%|████████▎ | 199/240 [08:16<01:32,  2.25s/it]

Checking batch → 43 origins × 44 destinations = 1892 routes

Processing batches:  83%|████████▎ | 200/240 [08:18<01:16,  1.92s/it]

Checking batch → 37 origins × 58 destinations = 2146 routes

Processing batches:  84%|████████▍ | 201/240 [08:18<00:57,  1.47s/it]

Checking batch → 39 origins × 11 destinations = 429 routes

Processing batches:  84%|████████▍ | 202/240 [08:19<00:45,  1.20s/it]

Checking batch → 117 origins × 9 destinations = 1053 routes

Processing batches:  85%|████████▍ | 203/240 [08:19<00:35,  1.05it/s]

Checking batch → 49 origins × 53 destinations = 2597 routes

Processing batches:  85%|████████▌ | 204/240 [08:19<00:28,  1.24it/s]

Checking batch → 41 origins × 43 destinations = 1763 routes

Processing batches:  85%|████████▌ | 205/240 [08:20<00:24,  1.43it/s]

Checking batch → 91 origins × 26 destinations = 2366 routes

Processing batches:  86%|████████▌ | 206/240 [08:20<00:20,  1.64it/s]

Checking batch → 36 origins × 31 destinations = 1116 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  86%|████████▋ | 207/240 [08:22<00:26,  1.27it/s]

Checking batch → 46 origins × 57 destinations = 2622 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  87%|████████▋ | 208/240 [09:02<06:46, 12.72s/it]

Checking batch → 46 origins × 27 destinations = 1242 routes

Processing batches:  87%|████████▋ | 209/240 [09:02<04:39,  9.02s/it]

Checking batch → 33 origins × 52 destinations = 1716 routes

Processing batches:  88%|████████▊ | 210/240 [09:03<03:13,  6.44s/it]

Checking batch → 79 origins × 19 destinations = 1501 routes

Processing batches:  88%|████████▊ | 211/240 [09:03<02:14,  4.63s/it]

Checking batch → 48 origins × 16 destinations = 768 routes

Processing batches:  88%|████████▊ | 212/240 [09:04<01:34,  3.36s/it]

Checking batch → 49 origins × 54 destinations = 2646 routes

Processing batches:  89%|████████▉ | 213/240 [09:04<01:09,  2.58s/it]

Checking batch → 47 origins × 32 destinations = 1504 routes

Processing batches:  89%|████████▉ | 214/240 [09:05<00:50,  1.93s/it]

Checking batch → 39 origins × 45 destinations = 1755 routes

Processing batches:  90%|████████▉ | 215/240 [09:05<00:36,  1.48s/it]

Checking batch → 50 origins × 46 destinations = 2300 routes

Processing batches:  90%|█████████ | 216/240 [09:06<00:28,  1.17s/it]

Checking batch → 45 origins × 41 destinations = 1845 routes

Processing batches:  90%|█████████ | 217/240 [09:06<00:21,  1.05it/s]

Checking batch → 83 origins × 9 destinations = 747 routes

Processing batches:  91%|█████████ | 218/240 [09:07<00:17,  1.29it/s]

Checking batch → 107 origins × 16 destinations = 1712 routes

Processing batches:  91%|█████████▏| 219/240 [09:07<00:14,  1.50it/s]

Checking batch → 40 origins × 45 destinations = 1800 routes

Processing batches:  92%|█████████▏| 220/240 [09:07<00:11,  1.69it/s]

Checking batch → 38 origins × 36 destinations = 1368 routes

Processing batches:  92%|█████████▏| 221/240 [09:08<00:10,  1.83it/s]

Checking batch → 44 origins × 60 destinations = 2640 routes

Processing batches:  92%|█████████▎| 222/240 [09:08<00:09,  1.91it/s]

Checking batch → 36 origins × 55 destinations = 1980 routes

Processing batches:  93%|█████████▎| 223/240 [09:09<00:08,  2.01it/s]

Checking batch → 33 origins × 52 destinations = 1716 routes

Processing batches:  93%|█████████▎| 224/240 [09:09<00:07,  2.13it/s]

Checking batch → 41 origins × 40 destinations = 1640 routes

Processing batches:  94%|█████████▍| 225/240 [09:10<00:06,  2.16it/s]

Checking batch → 43 origins × 42 destinations = 1806 routes

Processing batches:  94%|█████████▍| 226/240 [09:10<00:06,  2.17it/s]

Checking batch → 33 origins × 53 destinations = 1749 routes

Processing batches:  95%|█████████▍| 227/240 [09:10<00:05,  2.25it/s]

Checking batch → 34 origins × 56 destinations = 1904 routes

Processing batches:  95%|█████████▌| 228/240 [09:11<00:05,  2.27it/s]

Checking batch → 33 origins × 65 destinations = 2145 routes

Processing batches:  95%|█████████▌| 229/240 [09:11<00:04,  2.30it/s]

Checking batch → 38 origins × 34 destinations = 1292 routes

Processing batches:  96%|█████████▌| 230/240 [09:12<00:04,  2.34it/s]

Checking batch → 30 origins × 58 destinations = 1740 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  96%|█████████▋| 231/240 [09:13<00:06,  1.30it/s]

Checking batch → 38 origins × 49 destinations = 1862 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  97%|█████████▋| 232/240 [09:15<00:08,  1.12s/it]

Checking batch → 33 origins × 63 destinations = 2079 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  97%|█████████▋| 233/240 [09:19<00:13,  1.96s/it]

Checking batch → 43 origins × 45 destinations = 1935 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  98%|█████████▊| 234/240 [10:21<01:58, 19.83s/it]

Checking batch → 43 origins × 49 destinations = 2107 routes

Processing batches:  98%|█████████▊| 235/240 [10:21<01:10, 14.09s/it]

Checking batch → 46 origins × 42 destinations = 1932 routes

Processing batches:  98%|█████████▊| 236/240 [10:22<00:39,  9.99s/it]

Checking batch → 71 origins × 16 destinations = 1136 routes

Processing batches:  99%|█████████▉| 237/240 [10:22<00:21,  7.11s/it]

Checking batch → 63 origins × 41 destinations = 2583 routes

Processing batches:  99%|█████████▉| 238/240 [10:23<00:10,  5.11s/it]

Checking batch → 75 origins × 28 destinations = 2100 routes

Processing batches: 100%|█████████▉| 239/240 [10:23<00:03,  3.70s/it]

Checking batch → 16 origins × 23 destinations = 368 routes

Processing batches: 100%|██████████| 240/240 [10:23<00:00,  2.60s/it]

In [13]:
# Save ORS distances for schools into dataframe
df = pd.DataFrame({
    "rental_id": all_rental_ids,
    "top_distances": all_distances,
    "top_school_ids": all_school_ids
})

df.head()

NameError: name 'all_rental_ids' is not defined

In [14]:
# Save final CSV
df.to_csv("rentals_distances_to_schools.csv", index=False)

NameError: name 'df' is not defined