In [40]:
# Install openrouteservice for first time users
# !pip install openrouteservice

In [41]:
import openrouteservice
import pandas as pd
import numpy as np
from tqdm import tqdm

In [42]:
# Load in rental data
rental = pd.read_csv("rea_data/domain/Data/vic_rentals_all_cleaned.csv")
rental_coords = rental[["listing_id", "lon","lat"]]
rental_coords.head()

   listing_id        lon        lat
0    16782629  144.87091 -37.830982
1    17471867  144.86755 -37.826218
2    17721851  144.86632 -37.831226
3    17725855  144.86768 -37.827423
4    17745057  144.86790 -37.826270

In [43]:
# Load in tram stop data
tram = pd.read_csv("data\metro_tram_stops.txt")
tram_coords = tram[["stop_id", "stop_lon","stop_lat"]]
tram_coords.head()

   stop_id    stop_lon   stop_lat
0    10311  145.028508 -37.862455
1    10371  145.025382 -37.862069
2     1083  144.898841 -37.769699
3    11285  145.022754 -37.861710
4     1185  145.043375 -37.864226

In [44]:
# Define Haversine distance function
def haversine_vec(lon1, lat1, lon2, lat2):
    """
    Compute distance (meters) between two points using vectorised Haversine formula
    """
    lon1_rad = np.radians(lon1)[:, np.newaxis]
    lat1_rad = np.radians(lat1)[:, np.newaxis]

    lon2_rad = np.radians(lon2)[np.newaxis, :]
    lat2_rad = np.radians(lat2)[np.newaxis, :]

    earth_mean_radius = 6371000
    phi1, phi2 = lat1_rad, lat2_rad
    dphi1 = lat2_rad - lat1_rad
    dlambda = lon2_rad - lon1_rad
    
    a = np.sin(dphi1/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))

    return earth_mean_radius * c

In [45]:
# Find top 5 closest tram stops for each rental
dist_matrix = haversine_vec(rental_coords["lon"].values, rental_coords["lat"].values, tram_coords["stop_lon"].values, tram_coords["stop_lat"].values)

top5_indices = np.argsort(dist_matrix, axis=1)[:,:5]

rental_coords["top5_idx"] = list(top5_indices)
rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

C:\Users\chinj\AppData\Local\Temp\ipykernel_19492\300191937.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_idx"] = list(top5_indices)
C:\Users\chinj\AppData\Local\Temp\ipykernel_19492\300191937.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

In [46]:
# Group results by their top 5 closest tram stops
groups = rental_coords.groupby("top5_tuple")["listing_id"].apply(list).reset_index()
groups["num_rentals"] = groups["listing_id"].apply(len)

In [ ]:
# API key for OpenRouteService (ORS); hidden here for privacy
API_KEY = NA # Replace NA with your actual key when running

# Initialize ORS client with the API key
client = openrouteservice.Client(key = API_KEY)

In [48]:
# Batch rentals to stay under API route limit
top_n_trams = 5
max_route_per_batch = 3500

batches = []
current_batch = []
current_batch_rentals = 0

# Loop over each group of rentals that share the same top 5 tram stops
for _, row in groups.iterrows():
    group_name = row["top5_tuple"]
    rentals = row["listing_id"]
    group_size = len(rentals)

    start = 0
    # Split group into chunks so that adding them won't exceed ORS route limit
    while start < group_size:
        # Estimate number of rentals allowed to add to current batch without exceeding ORS route limit
        num_groups_if_added = len(current_batch) + 1
        max_rentals_for_this_chunk = max(
            (max_route_per_batch // (num_groups_if_added * top_n_trams)) - current_batch_rentals,
            1
        )

        # Determine slice of rentals for this chunk
        end = min(start + max_rentals_for_this_chunk, group_size)
        chunk = rentals[start:end]

        # Compute estimated number of routes if this chunk is added
        num_origins = current_batch_rentals + len(chunk)
        num_destinations = num_groups_if_added * top_n_trams
        estimated_routes = num_origins * num_destinations

        # Start new batch if adding this chunk exceeds ORS route limit
        if estimated_routes >= max_route_per_batch: 
            if current_batch:
                batches.append(current_batch)
            current_batch = [(group_name, chunk)]     
            current_batch_rentals = len(chunk)
        else:
            # Add chunk to batch otherwise
            current_batch.append((group_name, chunk))
            current_batch_rentals += len(chunk)
        start = end

# Append last batch if there are any remaining rentals
if current_batch:
        batches.append(current_batch)

print(f"Created {len(batches)} batches with full ORS route limit logic.")

Created 151 batches with full ORS route limit logic.

In [49]:
# Print and check summary of batches
for i, batch in enumerate(batches):
    num_groups = len(batch)
    num_rentals = sum(len(rentals) for _, rentals in batch)
    print(f"Batch {i+1}: {num_groups} groups, {num_rentals} rentals")

Batch 1: 16 groups, 43 rentals
Batch 2: 11 groups, 58 rentals
Batch 3: 19 groups, 36 rentals
Batch 4: 20 groups, 33 rentals
Batch 5: 17 groups, 41 rentals
Batch 6: 24 groups, 28 rentals
Batch 7: 21 groups, 33 rentals
Batch 8: 18 groups, 38 rentals
Batch 9: 18 groups, 38 rentals
Batch 10: 14 groups, 47 rentals
Batch 11: 13 groups, 53 rentals
Batch 12: 12 groups, 54 rentals
Batch 13: 16 groups, 43 rentals
Batch 14: 12 groups, 55 rentals
Batch 15: 19 groups, 30 rentals
Batch 16: 6 groups, 69 rentals
Batch 17: 4 groups, 120 rentals
Batch 18: 3 groups, 233 rentals
Batch 19: 4 groups, 160 rentals
Batch 20: 9 groups, 75 rentals
Batch 21: 4 groups, 123 rentals
Batch 22: 3 groups, 204 rentals
Batch 23: 19 groups, 34 rentals
Batch 24: 1 groups, 1 rentals
Batch 25: 1 groups, 349 rentals
Batch 26: 7 groups, 88 rentals
Batch 27: 12 groups, 58 rentals
Batch 28: 4 groups, 62 rentals
Batch 29: 3 groups, 210 rentals
Batch 30: 9 groups, 77 rentals
Batch 31: 8 groups, 87 rentals
Batch 32: 4 groups, 150 rentals
Batch 33: 6 groups, 113 rentals
Batch 34: 22 groups, 31 rentals
Batch 35: 12 groups, 58 rentals
Batch 36: 6 groups, 116 rentals
Batch 37: 14 groups, 49 rentals
Batch 38: 13 groups, 53 rentals
Batch 39: 13 groups, 52 rentals
Batch 40: 15 groups, 46 rentals
Batch 41: 11 groups, 62 rentals
Batch 42: 13 groups, 53 rentals
Batch 43: 16 groups, 42 rentals
Batch 44: 15 groups, 45 rentals
Batch 45: 13 groups, 50 rentals
Batch 46: 18 groups, 38 rentals
Batch 47: 7 groups, 89 rentals
Batch 48: 10 groups, 64 rentals
Batch 49: 13 groups, 50 rentals
Batch 50: 17 groups, 41 rentals
Batch 51: 17 groups, 41 rentals
Batch 52: 16 groups, 42 rentals
Batch 53: 18 groups, 38 rentals
Batch 54: 12 groups, 58 rentals
Batch 55: 13 groups, 53 rentals
Batch 56: 14 groups, 49 rentals
Batch 57: 16 groups, 42 rentals
Batch 58: 24 groups, 26 rentals
Batch 59: 16 groups, 43 rentals
Batch 60: 6 groups, 116 rentals
Batch 61: 3 groups, 223 rentals
Batch 62: 15 groups, 46 rentals
Batch 63: 11 groups, 63 rentals
Batch 64: 3 groups, 233 rentals
Batch 65: 1 groups, 1 rentals
Batch 66: 1 groups, 349 rentals
Batch 67: 3 groups, 145 rentals
Batch 68: 9 groups, 74 rentals
Batch 69: 22 groups, 30 rentals
Batch 70: 15 groups, 46 rentals
Batch 71: 16 groups, 41 rentals
Batch 72: 15 groups, 46 rentals
Batch 73: 21 groups, 31 rentals
Batch 74: 23 groups, 30 rentals
Batch 75: 20 groups, 33 rentals
Batch 76: 15 groups, 46 rentals
Batch 77: 13 groups, 53 rentals
Batch 78: 15 groups, 46 rentals
Batch 79: 19 groups, 32 rentals
Batch 80: 20 groups, 33 rentals
Batch 81: 18 groups, 36 rentals
Batch 82: 17 groups, 41 rentals
Batch 83: 14 groups, 49 rentals
Batch 84: 18 groups, 37 rentals
Batch 85: 16 groups, 43 rentals
Batch 86: 18 groups, 36 rentals
Batch 87: 17 groups, 38 rentals
Batch 88: 21 groups, 33 rentals
Batch 89: 19 groups, 36 rentals
Batch 90: 23 groups, 29 rentals
Batch 91: 17 groups, 41 rentals
Batch 92: 16 groups, 43 rentals
Batch 93: 16 groups, 41 rentals
Batch 94: 20 groups, 34 rentals
Batch 95: 18 groups, 38 rentals
Batch 96: 10 groups, 67 rentals
Batch 97: 14 groups, 49 rentals
Batch 98: 18 groups, 38 rentals
Batch 99: 3 groups, 188 rentals
Batch 100: 11 groups, 61 rentals
Batch 101: 24 groups, 29 rentals
Batch 102: 15 groups, 43 rentals
Batch 103: 14 groups, 49 rentals
Batch 104: 13 groups, 53 rentals
Batch 105: 6 groups, 116 rentals
Batch 106: 1 groups, 1 rentals
Batch 107: 1 groups, 349 rentals
Batch 108: 1 groups, 1 rentals
Batch 109: 1 groups, 349 rentals
Batch 110: 5 groups, 124 rentals
Batch 111: 12 groups, 54 rentals
Batch 112: 15 groups, 43 rentals
Batch 113: 21 groups, 31 rentals
Batch 114: 17 groups, 38 rentals
Batch 115: 17 groups, 38 rentals
Batch 116: 17 groups, 41 rentals
Batch 117: 15 groups, 46 rentals
Batch 118: 15 groups, 43 rentals
Batch 119: 12 groups, 57 rentals
Batch 120: 12 groups, 56 rentals
Batch 121: 9 groups, 77 rentals
Batch 122: 1 groups, 1 rentals
Batch 123: 1 groups, 349 rentals
Batch 124: 1 groups, 1 rentals
Batch 125: 1 groups, 349 rentals
Batch 126: 1 groups, 1 rentals
Batch 127: 1 groups, 349 rentals
Batch 128: 1 groups, 1 rentals
Batch 129: 1 groups, 349 rentals
Batch 130: 4 groups, 139 rentals
Batch 131: 21 groups, 32 rentals
Batch 132: 22 groups, 31 rentals
Batch 133: 23 groups, 30 rentals
Batch 134: 12 groups, 58 rentals
Batch 135: 1 groups, 1 rentals
Batch 136: 1 groups, 349 rentals
Batch 137: 1 groups, 1 rentals
Batch 138: 1 groups, 349 rentals
Batch 139: 3 groups, 182 rentals
Batch 140: 13 groups, 48 rentals
Batch 141: 16 groups, 43 rentals
Batch 142: 15 groups, 46 rentals
Batch 143: 12 groups, 58 rentals
Batch 144: 10 groups, 66 rentals
Batch 145: 12 groups, 54 rentals
Batch 146: 16 groups, 41 rentals
Batch 147: 16 groups, 41 rentals
Batch 148: 19 groups, 36 rentals
Batch 149: 15 groups, 44 rentals
Batch 150: 19 groups, 36 rentals
Batch 151: 13 groups, 26 rentals

In [50]:
# Call ORS to get distance to closest tram stops
all_rental_ids = []
all_distances = []
all_tram_ids = []

for batch in tqdm(batches, desc="Processing batches"):
    batch_rentals = [r for _, rentals in batch for r in rentals]
    batch_coords = rental_coords.set_index("listing_id").loc[batch_rentals][["lon", "lat"]].values.tolist()

    batch_tram_indices = [
        rental_coords.loc[rental_coords["listing_id"]==r, "top5_idx"].values[0] for r in batch_rentals
    ]

    unique_tram_indices = list(set(idx for indices in batch_tram_indices for idx in indices))

    origins = batch_coords
    destinations = tram_coords.loc[tram_coords.index.isin(unique_tram_indices)][["stop_lon", "stop_lat"]].values.tolist()
    dest_ids_map = {idx: tram_coords["stop_id"].iloc[idx] for idx in unique_tram_indices}
   
    tram_pos_map = {idx: i for i, idx in enumerate(unique_tram_indices)}

    num_origins = len(origins)
    num_destinations = len(destinations)
    num_routes = num_origins * num_destinations
    print(f"Checking batch → {num_origins} origins × {num_destinations} destinations = {num_routes} routes")

    # Call ORS distance matrix
    matrix = client.distance_matrix(
        locations = origins + destinations,
        profile = "driving-car",
        metrics = ["distance"],
        sources = list(range(len(origins))),
        destinations = list(range(len(origins), len(origins)+len(destinations)))
    )

    # Extract distances and tram stop IDs for top 5 tram stops
    for i, rental in enumerate(batch_rentals):
        top_indices = batch_tram_indices[i]
        dest_positions = [tram_pos_map[idx] for idx in top_indices]
        rental_distances = [matrix["distances"][i][pos] for pos in dest_positions]
        rental_tram_ids = [dest_ids_map[idx] for idx in top_indices]

        sorted_idx = np.argsort(rental_distances)
        top_n_distances = [rental_distances[k] for k in sorted_idx]
        top_n_ids = [rental_tram_ids[k] for k in sorted_idx]

        all_rental_ids.append(batch_rentals[i])
        all_distances.append(top_n_distances)
        all_tram_ids.append(top_n_ids)

Processing batches:   0%|          | 0/151 [00:00<?, ?it/s]

Checking batch → 43 origins × 40 destinations = 1720 routes

Processing batches:   1%|          | 1/151 [00:01<04:51,  1.94s/it]

Checking batch → 58 origins × 24 destinations = 1392 routes

Processing batches:   1%|▏         | 2/151 [00:08<11:37,  4.68s/it]

Checking batch → 36 origins × 41 destinations = 1476 routes

Processing batches:   2%|▏         | 3/151 [00:09<06:50,  2.77s/it]

Checking batch → 33 origins × 40 destinations = 1320 routes

Processing batches:   3%|▎         | 4/151 [00:09<05:01,  2.05s/it]

Checking batch → 41 origins × 29 destinations = 1189 routes

Processing batches:   3%|▎         | 5/151 [00:10<03:38,  1.50s/it]

Checking batch → 28 origins × 45 destinations = 1260 routes

Processing batches:   4%|▍         | 6/151 [00:10<02:42,  1.12s/it]

Checking batch → 33 origins × 47 destinations = 1551 routes

Processing batches:   5%|▍         | 7/151 [00:11<02:07,  1.13it/s]

Checking batch → 38 origins × 40 destinations = 1520 routes

Processing batches:   5%|▌         | 8/151 [00:12<02:06,  1.13it/s]

Checking batch → 38 origins × 55 destinations = 2090 routes

Processing batches:   6%|▌         | 9/151 [00:13<02:16,  1.04it/s]

Checking batch → 47 origins × 37 destinations = 1739 routes

Processing batches:   7%|▋         | 10/151 [00:14<02:09,  1.09it/s]

Checking batch → 53 origins × 18 destinations = 954 routes

Processing batches:   7%|▋         | 11/151 [00:15<02:06,  1.10it/s]

Checking batch → 54 origins × 21 destinations = 1134 routes

Processing batches:   8%|▊         | 12/151 [00:16<02:13,  1.04it/s]

Checking batch → 43 origins × 30 destinations = 1290 routes

Processing batches:   9%|▊         | 13/151 [00:17<02:10,  1.06it/s]

Checking batch → 55 origins × 20 destinations = 1100 routes

Processing batches:   9%|▉         | 14/151 [00:18<02:12,  1.03it/s]

Checking batch → 30 origins × 57 destinations = 1710 routes

Processing batches:  10%|▉         | 15/151 [00:19<02:24,  1.07s/it]

Checking batch → 69 origins × 9 destinations = 621 routes

Processing batches:  11%|█         | 16/151 [00:19<02:00,  1.12it/s]

Checking batch → 120 origins × 11 destinations = 1320 routes

Processing batches:  11%|█▏        | 17/151 [00:20<01:42,  1.31it/s]

Checking batch → 233 origins × 6 destinations = 1398 routes

Processing batches:  12%|█▏        | 18/151 [00:20<01:27,  1.51it/s]

Checking batch → 160 origins × 7 destinations = 1120 routes

Processing batches:  13%|█▎        | 19/151 [00:21<01:17,  1.69it/s]

Checking batch → 75 origins × 15 destinations = 1125 routes

Processing batches:  13%|█▎        | 20/151 [00:21<01:15,  1.73it/s]

Checking batch → 123 origins × 8 destinations = 984 routes

Processing batches:  14%|█▍        | 21/151 [00:22<01:09,  1.88it/s]

Checking batch → 204 origins × 6 destinations = 1224 routes

Processing batches:  15%|█▍        | 22/151 [00:22<01:04,  2.00it/s]

Checking batch → 34 origins × 22 destinations = 748 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  15%|█▌        | 23/151 [00:23<01:32,  1.38it/s]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  16%|█▌        | 24/151 [00:24<01:17,  1.63it/s]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  17%|█▋        | 25/151 [00:24<01:21,  1.54it/s]

Checking batch → 88 origins × 10 destinations = 880 routes

Processing batches:  17%|█▋        | 26/151 [00:25<01:10,  1.77it/s]

Checking batch → 58 origins × 11 destinations = 638 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  18%|█▊        | 27/151 [01:16<32:38, 15.79s/it]

Checking batch → 62 origins × 6 destinations = 372 routes

Processing batches:  19%|█▊        | 28/151 [01:16<22:53, 11.16s/it]

Checking batch → 210 origins × 6 destinations = 1260 routes

Processing batches:  19%|█▉        | 29/151 [01:17<16:18,  8.02s/it]

Checking batch → 77 origins × 14 destinations = 1078 routes

Processing batches:  20%|█▉        | 30/151 [01:23<14:44,  7.31s/it]

Checking batch → 87 origins × 8 destinations = 696 routes

Processing batches:  21%|██        | 31/151 [01:23<10:27,  5.23s/it]

Checking batch → 150 origins × 6 destinations = 900 routes

Processing batches:  21%|██        | 32/151 [01:24<07:29,  3.78s/it]

Checking batch → 113 origins × 13 destinations = 1469 routes

Processing batches:  22%|██▏       | 33/151 [01:24<05:26,  2.76s/it]

Checking batch → 31 origins × 33 destinations = 1023 routes

Processing batches:  23%|██▎       | 34/151 [01:24<03:59,  2.05s/it]

Checking batch → 58 origins × 17 destinations = 986 routes

Processing batches:  23%|██▎       | 35/151 [01:30<06:01,  3.11s/it]

Checking batch → 116 origins × 11 destinations = 1276 routes

Processing batches:  24%|██▍       | 36/151 [01:30<04:23,  2.29s/it]

Checking batch → 49 origins × 21 destinations = 1029 routes

Processing batches:  25%|██▍       | 37/151 [01:31<03:15,  1.72s/it]

Checking batch → 53 origins × 20 destinations = 1060 routes

Processing batches:  25%|██▌       | 38/151 [01:31<02:28,  1.31s/it]

Checking batch → 52 origins × 23 destinations = 1196 routes

Processing batches:  26%|██▌       | 39/151 [01:31<01:55,  1.03s/it]

Checking batch → 46 origins × 34 destinations = 1564 routes

Processing batches:  26%|██▋       | 40/151 [01:32<01:33,  1.19it/s]

Checking batch → 62 origins × 25 destinations = 1550 routes

Processing batches:  27%|██▋       | 41/151 [01:32<01:17,  1.41it/s]

Checking batch → 53 origins × 20 destinations = 1060 routes

Processing batches:  28%|██▊       | 42/151 [01:33<01:06,  1.65it/s]

Checking batch → 42 origins × 27 destinations = 1134 routes

Processing batches:  28%|██▊       | 43/151 [01:33<00:58,  1.84it/s]

Checking batch → 45 origins × 20 destinations = 900 routes

Processing batches:  29%|██▉       | 44/151 [01:33<00:52,  2.03it/s]

Checking batch → 50 origins × 42 destinations = 2100 routes

Processing batches:  30%|██▉       | 45/151 [01:34<00:49,  2.13it/s]

Checking batch → 38 origins × 30 destinations = 1140 routes

Processing batches:  30%|███       | 46/151 [01:34<00:51,  2.04it/s]

Checking batch → 89 origins × 18 destinations = 1602 routes

Processing batches:  31%|███       | 47/151 [01:35<00:47,  2.20it/s]

Checking batch → 64 origins × 29 destinations = 1856 routes

Processing batches:  32%|███▏      | 48/151 [01:35<00:49,  2.08it/s]

Checking batch → 50 origins × 23 destinations = 1150 routes

Processing batches:  32%|███▏      | 49/151 [01:36<00:45,  2.23it/s]

Checking batch → 41 origins × 22 destinations = 902 routes

Processing batches:  33%|███▎      | 50/151 [01:36<00:42,  2.37it/s]

Checking batch → 41 origins × 31 destinations = 1271 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  34%|███▍      | 51/151 [01:39<02:12,  1.32s/it]

Checking batch → 42 origins × 26 destinations = 1092 routes

Processing batches:  34%|███▍      | 52/151 [01:40<01:42,  1.03s/it]

Checking batch → 38 origins × 22 destinations = 836 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  35%|███▌      | 53/151 [02:18<19:51, 12.16s/it]

Checking batch → 58 origins × 17 destinations = 986 routes

Processing batches:  36%|███▌      | 54/151 [02:18<13:56,  8.63s/it]

Checking batch → 53 origins × 27 destinations = 1431 routes

Processing batches:  36%|███▋      | 55/151 [02:19<09:50,  6.16s/it]

Checking batch → 49 origins × 20 destinations = 980 routes

Processing batches:  37%|███▋      | 56/151 [02:19<07:00,  4.42s/it]

Checking batch → 42 origins × 23 destinations = 966 routes

Processing batches:  38%|███▊      | 57/151 [02:19<05:01,  3.20s/it]

Checking batch → 26 origins × 41 destinations = 1066 routes

Processing batches:  38%|███▊      | 58/151 [02:20<03:38,  2.35s/it]

Checking batch → 43 origins × 17 destinations = 731 routes

Processing batches:  39%|███▉      | 59/151 [02:20<02:41,  1.75s/it]

Checking batch → 116 origins × 8 destinations = 928 routes

Processing batches:  40%|███▉      | 60/151 [02:20<02:01,  1.34s/it]

Checking batch → 223 origins × 6 destinations = 1338 routes

Processing batches:  40%|████      | 61/151 [02:21<01:35,  1.06s/it]

Checking batch → 46 origins × 19 destinations = 874 routes

Processing batches:  41%|████      | 62/151 [02:21<01:15,  1.17it/s]

Checking batch → 63 origins × 24 destinations = 1512 routes

Processing batches:  42%|████▏     | 63/151 [02:22<01:03,  1.39it/s]

Checking batch → 233 origins × 10 destinations = 2330 routes

Processing batches:  42%|████▏     | 64/151 [02:22<00:54,  1.59it/s]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  43%|████▎     | 65/151 [02:22<00:45,  1.88it/s]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  44%|████▎     | 66/151 [02:23<00:43,  1.96it/s]

Checking batch → 145 origins × 6 destinations = 870 routes

Processing batches:  44%|████▍     | 67/151 [02:23<00:39,  2.11it/s]

Checking batch → 74 origins × 15 destinations = 1110 routes

Processing batches:  45%|████▌     | 68/151 [02:24<00:37,  2.21it/s]

Checking batch → 30 origins × 34 destinations = 1020 routes

Processing batches:  46%|████▌     | 69/151 [02:24<00:34,  2.34it/s]

Checking batch → 46 origins × 32 destinations = 1472 routes

Processing batches:  46%|████▋     | 70/151 [02:24<00:33,  2.41it/s]

Checking batch → 41 origins × 39 destinations = 1599 routes

Processing batches:  47%|████▋     | 71/151 [02:25<00:32,  2.44it/s]

Checking batch → 46 origins × 20 destinations = 920 routes

Processing batches:  48%|████▊     | 72/151 [02:26<01:03,  1.24it/s]

Checking batch → 31 origins × 42 destinations = 1302 routes

Processing batches:  48%|████▊     | 73/151 [02:27<00:53,  1.46it/s]

Checking batch → 30 origins × 64 destinations = 1920 routes

Processing batches:  49%|████▉     | 74/151 [02:27<00:46,  1.66it/s]

Checking batch → 33 origins × 57 destinations = 1881 routes

Processing batches:  50%|████▉     | 75/151 [02:28<00:41,  1.84it/s]

Checking batch → 46 origins × 23 destinations = 1058 routes

Processing batches:  50%|█████     | 76/151 [02:28<00:36,  2.06it/s]

Checking batch → 53 origins × 17 destinations = 901 routes

Processing batches:  51%|█████     | 77/151 [02:28<00:32,  2.25it/s]

Checking batch → 46 origins × 23 destinations = 1058 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  52%|█████▏    | 78/151 [02:30<01:05,  1.11it/s]

Checking batch → 32 origins × 38 destinations = 1216 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 9th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  52%|█████▏    | 79/151 [03:47<28:14, 23.54s/it]

Checking batch → 33 origins × 23 destinations = 759 routes

Processing batches:  53%|█████▎    | 80/151 [03:47<19:37, 16.59s/it]

Checking batch → 36 origins × 30 destinations = 1080 routes

Processing batches:  54%|█████▎    | 81/151 [03:47<13:41, 11.73s/it]

Checking batch → 41 origins × 36 destinations = 1476 routes

Processing batches:  54%|█████▍    | 82/151 [03:48<09:36,  8.36s/it]

Checking batch → 49 origins × 19 destinations = 931 routes

Processing batches:  55%|█████▍    | 83/151 [03:48<06:45,  5.96s/it]

Checking batch → 37 origins × 40 destinations = 1480 routes

Processing batches:  56%|█████▌    | 84/151 [03:49<04:47,  4.29s/it]

Checking batch → 43 origins × 27 destinations = 1161 routes

Processing batches:  56%|█████▋    | 85/151 [03:49<03:25,  3.12s/it]

Checking batch → 36 origins × 40 destinations = 1440 routes

Processing batches:  57%|█████▋    | 86/151 [03:50<02:29,  2.31s/it]

Checking batch → 38 origins × 26 destinations = 988 routes

Processing batches:  58%|█████▊    | 87/151 [03:50<01:50,  1.73s/it]

Checking batch → 33 origins × 36 destinations = 1188 routes

Processing batches:  58%|█████▊    | 88/151 [03:50<01:23,  1.33s/it]

Checking batch → 36 origins × 31 destinations = 1116 routes

Processing batches:  59%|█████▉    | 89/151 [03:51<01:04,  1.04s/it]

Checking batch → 29 origins × 46 destinations = 1334 routes

Processing batches:  60%|█████▉    | 90/151 [03:51<00:51,  1.19it/s]

Checking batch → 41 origins × 56 destinations = 2296 routes

Processing batches:  60%|██████    | 91/151 [03:51<00:43,  1.39it/s]

Checking batch → 43 origins × 23 destinations = 989 routes

Processing batches:  61%|██████    | 92/151 [03:52<00:36,  1.64it/s]

Checking batch → 41 origins × 18 destinations = 738 routes

Processing batches:  62%|██████▏   | 93/151 [03:52<00:31,  1.87it/s]

Checking batch → 34 origins × 41 destinations = 1394 routes

Processing batches:  62%|██████▏   | 94/151 [03:53<00:28,  2.01it/s]

Checking batch → 38 origins × 38 destinations = 1444 routes

Processing batches:  63%|██████▎   | 95/151 [03:53<00:26,  2.13it/s]

Checking batch → 67 origins × 30 destinations = 2010 routes

Processing batches:  64%|██████▎   | 96/151 [03:53<00:25,  2.13it/s]

Checking batch → 49 origins × 25 destinations = 1225 routes

Processing batches:  64%|██████▍   | 97/151 [03:54<00:24,  2.19it/s]

Checking batch → 38 origins × 40 destinations = 1520 routes

Processing batches:  65%|██████▍   | 98/151 [03:54<00:24,  2.16it/s]

Checking batch → 188 origins × 6 destinations = 1128 routes

Processing batches:  66%|██████▌   | 99/151 [03:55<00:23,  2.24it/s]

Checking batch → 61 origins × 17 destinations = 1037 routes

Processing batches:  66%|██████▌   | 100/151 [03:55<00:21,  2.37it/s]

Checking batch → 29 origins × 48 destinations = 1392 routes

Processing batches:  67%|██████▋   | 101/151 [04:02<01:55,  2.31s/it]

Checking batch → 43 origins × 30 destinations = 1290 routes

Processing batches:  68%|██████▊   | 102/151 [04:02<01:25,  1.74s/it]

Checking batch → 49 origins × 21 destinations = 1029 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  68%|██████▊   | 103/151 [04:05<01:32,  1.92s/it]

Checking batch → 53 origins × 16 destinations = 848 routes

Processing batches:  69%|██████▉   | 104/151 [04:05<01:08,  1.45s/it]

Checking batch → 116 origins × 9 destinations = 1044 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  70%|██████▉   | 105/151 [04:51<11:21, 14.82s/it]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  70%|███████   | 106/151 [04:51<07:50, 10.47s/it]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  71%|███████   | 107/151 [04:52<05:32,  7.55s/it]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  72%|███████▏  | 108/151 [04:52<03:51,  5.38s/it]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  72%|███████▏  | 109/151 [04:53<02:44,  3.91s/it]

Checking batch → 124 origins × 7 destinations = 868 routes

Processing batches:  73%|███████▎  | 110/151 [04:53<01:57,  2.86s/it]

Checking batch → 54 origins × 24 destinations = 1296 routes

Processing batches:  74%|███████▎  | 111/151 [04:54<01:24,  2.12s/it]

Checking batch → 43 origins × 25 destinations = 1075 routes

Processing batches:  74%|███████▍  | 112/151 [04:54<01:02,  1.60s/it]

Checking batch → 31 origins × 64 destinations = 1984 routes

Processing batches:  75%|███████▍  | 113/151 [04:55<00:47,  1.26s/it]

Checking batch → 38 origins × 45 destinations = 1710 routes

Processing batches:  75%|███████▌  | 114/151 [04:55<00:37,  1.02s/it]

Checking batch → 38 origins × 29 destinations = 1102 routes

Processing batches:  76%|███████▌  | 115/151 [04:55<00:29,  1.22it/s]

Checking batch → 41 origins × 33 destinations = 1353 routes

Processing batches:  77%|███████▋  | 116/151 [04:56<00:23,  1.46it/s]

Checking batch → 46 origins × 20 destinations = 920 routes

Processing batches:  77%|███████▋  | 117/151 [04:56<00:20,  1.69it/s]

Checking batch → 43 origins × 14 destinations = 602 routes

Processing batches:  78%|███████▊  | 118/151 [04:56<00:17,  1.92it/s]

Checking batch → 57 origins × 14 destinations = 798 routes

Processing batches:  79%|███████▉  | 119/151 [04:57<00:14,  2.14it/s]

Checking batch → 56 origins × 13 destinations = 728 routes

Processing batches:  79%|███████▉  | 120/151 [04:57<00:13,  2.28it/s]

Checking batch → 77 origins × 10 destinations = 770 routes

Processing batches:  80%|████████  | 121/151 [04:58<00:12,  2.39it/s]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  81%|████████  | 122/151 [04:58<00:11,  2.60it/s]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  81%|████████▏ | 123/151 [04:58<00:11,  2.44it/s]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  82%|████████▏ | 124/151 [04:59<00:10,  2.61it/s]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  83%|████████▎ | 125/151 [04:59<00:10,  2.38it/s]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  83%|████████▎ | 126/151 [04:59<00:09,  2.58it/s]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  84%|████████▍ | 127/151 [05:00<00:10,  2.39it/s]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  85%|████████▍ | 128/151 [05:00<00:09,  2.41it/s]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  85%|████████▌ | 129/151 [05:01<00:09,  2.32it/s]

Checking batch → 139 origins × 15 destinations = 2085 routes

Processing batches:  86%|████████▌ | 130/151 [05:01<00:08,  2.33it/s]

Checking batch → 32 origins × 57 destinations = 1824 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  87%|████████▋ | 131/151 [06:06<06:37, 19.87s/it]

Checking batch → 31 origins × 38 destinations = 1178 routes

Processing batches:  87%|████████▋ | 132/151 [06:07<04:26, 14.03s/it]

Checking batch → 30 origins × 43 destinations = 1290 routes

Processing batches:  88%|████████▊ | 133/151 [06:07<02:58,  9.94s/it]

Checking batch → 58 origins × 20 destinations = 1160 routes

Processing batches:  89%|████████▊ | 134/151 [06:08<02:00,  7.06s/it]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  89%|████████▉ | 135/151 [06:08<01:20,  5.04s/it]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  90%|█████████ | 136/151 [06:14<01:20,  5.38s/it]

Checking batch → 1 origins × 5 destinations = 5 routes

Processing batches:  91%|█████████ | 137/151 [06:14<00:54,  3.86s/it]

Checking batch → 349 origins × 5 destinations = 1745 routes

Processing batches:  91%|█████████▏| 138/151 [06:15<00:36,  2.84s/it]

Checking batch → 182 origins × 6 destinations = 1092 routes

Processing batches:  92%|█████████▏| 139/151 [06:17<00:30,  2.54s/it]

Checking batch → 48 origins × 11 destinations = 528 routes

Processing batches:  93%|█████████▎| 140/151 [06:17<00:20,  1.88s/it]

Checking batch → 43 origins × 16 destinations = 688 routes

Processing batches:  93%|█████████▎| 141/151 [06:17<00:14,  1.43s/it]

Checking batch → 46 origins × 15 destinations = 690 routes

Processing batches:  94%|█████████▍| 142/151 [06:18<00:09,  1.10s/it]

Checking batch → 58 origins × 11 destinations = 638 routes

Processing batches:  95%|█████████▍| 143/151 [06:18<00:07,  1.14it/s]

Checking batch → 66 origins × 11 destinations = 726 routes

Processing batches:  95%|█████████▌| 144/151 [06:18<00:05,  1.39it/s]

Checking batch → 54 origins × 15 destinations = 810 routes

Processing batches:  96%|█████████▌| 145/151 [06:19<00:03,  1.63it/s]

Checking batch → 41 origins × 19 destinations = 779 routes

Processing batches:  97%|█████████▋| 146/151 [06:19<00:02,  1.87it/s]

Checking batch → 41 origins × 18 destinations = 738 routes

Processing batches:  97%|█████████▋| 147/151 [06:20<00:01,  2.09it/s]

Checking batch → 36 origins × 34 destinations = 1224 routes

Processing batches:  98%|█████████▊| 148/151 [06:20<00:01,  2.21it/s]

Checking batch → 44 origins × 17 destinations = 748 routes

Processing batches:  99%|█████████▊| 149/151 [06:20<00:00,  2.36it/s]

Checking batch → 36 origins × 21 destinations = 756 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  99%|█████████▉| 150/151 [06:22<00:00,  1.44it/s]

Checking batch → 26 origins × 28 destinations = 728 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches: 100%|██████████| 151/151 [06:24<00:00,  2.54s/it]

In [51]:
# Save ORS distances for tram stops into dataframe
df = pd.DataFrame({
    "rental_id": all_rental_ids,
    "top_distances": all_distances,
    "top_tram_ids": all_tram_ids
})

df.head()

,rental_id,top_distances,top_tram_ids
0,17745632,"[85.48, 125.58, 130.44, 1160.58, 1385.31]","[950, 9156, 10311, 20528, 20529]"
1,17682583,"[85.48, 125.58, 130.44, 1160.58, 1385.31]","[950, 9156, 10311, 20528, 20529]"
2,17640056,"[115.94, 378.13, 428.06, 20694.89, 23743.12]","[18487, 992, 18486, 1083, 18485]"
3,17727285,"[468.24, 730.43, 780.36, 21047.19, 24095.41]","[18487, 992, 18486, 1083, 18485]"
4,17674738,"[435.43, 627.47, 939.6, 11287.8, 21206.42]","[18488, 18487, 18486, 4945, 1083]"

In [52]:
# Save final CSV
df.to_csv("rentals_distances_to_tram_stops.csv", index=False)