In [117]:
# Install openrouteservice for first time users
# !pip install openrouteservice

In [ ]:
import openrouteservice
import pandas as pd
import numpy as np
from tqdm import tqdm

In [118]:
# Load in rental data
rental = pd.read_csv("rea_data/domain/Data/vic_rentals_all_cleaned.csv")
rental_coords = rental[["listing_id", "lon","lat"]]
rental_coords.head()

   listing_id        lon        lat
0    16782629  144.87091 -37.830982
1    17471867  144.86755 -37.826218
2    17721851  144.86632 -37.831226
3    17725855  144.86768 -37.827423
4    17745057  144.86790 -37.826270

In [ ]:
# Load in train stops data
train = pd.read_csv("data\metro_train_stops.txt")
station_coords = train[["stop_id", "stop_lon","stop_lat"]]
station_coords.head()

  stop_id    stop_lon   stop_lat
0   10117  145.112473 -37.873763
1   10920  144.956043 -37.811880
2   10921  144.955968 -37.811725
3   10922  144.962513 -37.809973
4   10923  144.962505 -37.809865

In [ ]:
# Define Haversine distance function
def haversine(lon1, lat1, lon2, lat2):
    """
    Compute distance (meters) between two points using Haversine formula
    """
    earth_mean_radius = 6371000
    phi1, phi2 = np.radians(lat1), np.radians(lat2)
    dphi1 = np.radians(lat2 - lat1)
    dlambda = np.radians(lon2 - lon1)
    
    a = np.sin(dphi1/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))

    return earth_mean_radius * c

In [122]:
# Find top 3 closest train stops for each rental
closest_3 = []
for r_lon, r_lat in rental_coords[["lon", "lat"]].values:
    distances = [haversine(r_lon, r_lat, s_lon, s_lat) for s_lon , s_lat in station_coords[["stop_lon", "stop_lat"]].values]
    indices = np.argsort(distances)[:3]
    closest_3.append(indices)

rental_coords["top3_idx"] = closest_3
rental_coords["top3_tuple"] = rental_coords["top3_idx"].apply(lambda x: tuple(sorted(x)))

C:\Users\chinj\AppData\Local\Temp\ipykernel_10832\3355039345.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top3_idx"] = closest_3
C:\Users\chinj\AppData\Local\Temp\ipykernel_10832\3355039345.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top3_tuple"] = rental_coords["top3_idx"].apply(lambda x: tuple(sorted(x)))

In [ ]:
# Group results by their top 3 closest train stops
groups = rental_coords.groupby("top3_tuple")["listing_id"].apply(list).reset_index()
groups["num_rentals"] = groups["listing_id"].apply(len)

In [ ]:
# API key for OpenRouteService (ORS); hidden here for privacy
API_KEY = NA # Replace NA with your actual key when running

# Initialize ORS client with the API key
client = openrouteservice.Client(key = API_KEY)

In [124]:
# Batch rentals to stay under API route limit
top_n_stations = 3
max_route_per_batch = 3500

batches = []
current_batch = []
current_batch_rentals = 0

# Loop over each group of rentals that share the same top 3 train stops
for _, row in groups.iterrows():
    group_name = row["top3_tuple"]
    rentals = row["listing_id"]
    group_size = len(rentals)

    start = 0
    # Split group into chunks so that adding them won't exceed ORS route limit
    while start < group_size:
        # Estimate number of rentals allowed to add to current batch without exceeding ORS route limit
        num_groups_if_added = len(current_batch) + 1
        max_rentals_for_this_chunk = max(
            (max_route_per_batch // (num_groups_if_added * top_n_stations)) - current_batch_rentals,
            1
        )

        # Determine slice of rentals for this chunk
        end = min(start + max_rentals_for_this_chunk, group_size)
        chunk = rentals[start:end]

        # Compute estimated number of routes if this chunk is added
        num_origins = current_batch_rentals + len(chunk)
        num_destinations = num_groups_if_added * top_n_stations
        estimated_routes = num_origins * num_destinations

        # Start new batch if adding this chunk exceeds ORS route limit
        if estimated_routes >= max_route_per_batch: 
            if current_batch:
                batches.append(current_batch)
            current_batch = [(group_name, chunk)]     
            current_batch_rentals = len(chunk)
        else:
            # Add chunk to batch otherwise
            current_batch.append((group_name, chunk))
            current_batch_rentals += len(chunk)
        start = end

# Append last batch if there are any remaining rentals
if current_batch:
        batches.append(current_batch)

print(f"Created {len(batches)} batches with full ORS route limit logic.")

Created 94 batches with full ORS route limit logic.

In [ ]:
# Print and check summary of batches
for i, batch in enumerate(batches):
    num_groups = len(batch)
    num_rentals = sum(len(rentals) for _, rentals in batch)
    print(f"Batch {i+1}: {num_groups} groups, {num_rentals} rentals")

Batch 1: 9 groups, 124 rentals
Batch 2: 13 groups, 88 rentals
Batch 3: 14 groups, 79 rentals
Batch 4: 8 groups, 145 rentals
Batch 5: 14 groups, 83 rentals
Batch 6: 14 groups, 83 rentals
Batch 7: 19 groups, 61 rentals
Batch 8: 15 groups, 77 rentals
Batch 9: 9 groups, 125 rentals
Batch 10: 9 groups, 129 rentals
Batch 11: 7 groups, 166 rentals
Batch 12: 9 groups, 129 rentals
Batch 13: 7 groups, 166 rentals
Batch 14: 6 groups, 189 rentals
Batch 15: 9 groups, 129 rentals
Batch 16: 8 groups, 141 rentals
Batch 17: 12 groups, 97 rentals
Batch 18: 12 groups, 97 rentals
Batch 19: 8 groups, 145 rentals
Batch 20: 8 groups, 133 rentals
Batch 21: 11 groups, 106 rentals
Batch 22: 11 groups, 106 rentals
Batch 23: 11 groups, 106 rentals
Batch 24: 10 groups, 116 rentals
Batch 25: 10 groups, 116 rentals
Batch 26: 14 groups, 80 rentals
Batch 27: 9 groups, 129 rentals
Batch 28: 4 groups, 291 rentals
Batch 29: 4 groups, 291 rentals
Batch 30: 4 groups, 291 rentals
Batch 31: 7 groups, 166 rentals
Batch 32: 4 groups, 239 rentals
Batch 33: 16 groups, 71 rentals
Batch 34: 10 groups, 116 rentals
Batch 35: 9 groups, 129 rentals
Batch 36: 13 groups, 85 rentals
Batch 37: 19 groups, 60 rentals
Batch 38: 14 groups, 83 rentals
Batch 39: 15 groups, 77 rentals
Batch 40: 13 groups, 89 rentals
Batch 41: 12 groups, 90 rentals
Batch 42: 9 groups, 129 rentals
Batch 43: 5 groups, 233 rentals
Batch 44: 10 groups, 116 rentals
Batch 45: 8 groups, 132 rentals
Batch 46: 19 groups, 61 rentals
Batch 47: 12 groups, 94 rentals
Batch 48: 13 groups, 89 rentals
Batch 49: 11 groups, 102 rentals
Batch 50: 10 groups, 114 rentals
Batch 51: 15 groups, 77 rentals
Batch 52: 17 groups, 68 rentals
Batch 53: 13 groups, 89 rentals
Batch 54: 11 groups, 106 rentals
Batch 55: 3 groups, 388 rentals
Batch 56: 3 groups, 355 rentals
Batch 57: 8 groups, 145 rentals
Batch 58: 8 groups, 130 rentals
Batch 59: 16 groups, 71 rentals
Batch 60: 21 groups, 55 rentals
Batch 61: 13 groups, 89 rentals
Batch 62: 9 groups, 129 rentals
Batch 63: 9 groups, 119 rentals
Batch 64: 3 groups, 388 rentals
Batch 65: 9 groups, 129 rentals
Batch 66: 14 groups, 79 rentals
Batch 67: 14 groups, 83 rentals
Batch 68: 12 groups, 97 rentals
Batch 69: 12 groups, 97 rentals
Batch 70: 10 groups, 116 rentals
Batch 71: 12 groups, 92 rentals
Batch 72: 6 groups, 190 rentals
Batch 73: 25 groups, 46 rentals
Batch 74: 20 groups, 55 rentals
Batch 75: 14 groups, 80 rentals
Batch 76: 11 groups, 100 rentals
Batch 77: 12 groups, 92 rentals
Batch 78: 22 groups, 53 rentals
Batch 79: 15 groups, 77 rentals
Batch 80: 16 groups, 72 rentals
Batch 81: 16 groups, 68 rentals
Batch 82: 7 groups, 149 rentals
Batch 83: 3 groups, 352 rentals
Batch 84: 8 groups, 145 rentals
Batch 85: 9 groups, 129 rentals
Batch 86: 16 groups, 72 rentals
Batch 87: 12 groups, 92 rentals
Batch 88: 15 groups, 77 rentals
Batch 89: 18 groups, 63 rentals
Batch 90: 12 groups, 97 rentals
Batch 91: 5 groups, 233 rentals
Batch 92: 16 groups, 71 rentals
Batch 93: 23 groups, 49 rentals
Batch 94: 17 groups, 61 rentals

In [ ]:
# Call ORS to get distance to closest train stops
all_rental_ids = []
all_distances = []
all_station_ids = []

for batch in tqdm(batches, desc="Processing batches"):
    batch_rentals = [r for _, rentals in batch for r in rentals]
    batch_coords = rental_coords.set_index("listing_id").loc[batch_rentals][["lon", "lat"]].values.tolist()

    batch_station_indices = [
        rental_coords.loc[rental_coords["listing_id"]==r, "top3_idx"].values[0] for r in batch_rentals
    ]

    unique_station_indices = list(set(idx for indices in batch_station_indices for idx in indices))

    origins = batch_coords
    destinations = station_coords.loc[station_coords.index.isin(unique_station_indices)][["stop_lon", "stop_lat"]].values.tolist()
    dest_ids_map = {idx: station_coords["stop_id"].iloc[idx] for idx in unique_station_indices}
   
    station_pos_map = {idx: i for i, idx in enumerate(unique_station_indices)}

    num_origins = len(origins)
    num_destinations = len(destinations)
    num_routes = num_origins * num_destinations
    print(f"Checking batch → {num_origins} origins × {num_destinations} destinations = {num_routes} routes")

    # Call ORS distance matrix
    matrix = client.distance_matrix(
        locations = origins + destinations,
        profile = "driving-car",
        metrics = ["distance"],
        sources = list(range(len(origins))),
        destinations = list(range(len(origins), len(origins)+len(destinations)))
    )

    # Extract distances and train stop IDs for top 3 train stops
    for i, rental in enumerate(batch_rentals):
        top_indices = batch_station_indices[i]
        dest_positions = [station_pos_map[idx] for idx in top_indices]
        rental_distances = [matrix["distances"][i][pos] for pos in dest_positions]
        rental_station_ids = [dest_ids_map[idx] for idx in top_indices]

        sorted_idx = np.argsort(rental_distances)
        top_n_distances = [rental_distances[k] for k in sorted_idx]
        top_n_ids = [rental_station_ids[k] for k in sorted_idx]

        all_rental_ids.append(batch_rentals[i])
        all_distances.append(top_n_distances)
        all_station_ids.append(top_n_ids)

Processing batches:   0%|          | 0/94 [00:00<?, ?it/s]

Checking batch → 124 origins × 11 destinations = 1364 routes

Processing batches:   1%|          | 1/94 [00:02<03:11,  2.06s/it]

Checking batch → 88 origins × 22 destinations = 1936 routes

Processing batches:   2%|▏         | 2/94 [00:02<01:40,  1.09s/it]

Checking batch → 79 origins × 22 destinations = 1738 routes

Processing batches:   3%|▎         | 3/94 [00:02<01:11,  1.28it/s]

Checking batch → 145 origins × 14 destinations = 2030 routes

Processing batches:   4%|▍         | 4/94 [00:03<00:57,  1.56it/s]

Checking batch → 83 origins × 22 destinations = 1826 routes

Processing batches:   5%|▌         | 5/94 [00:03<00:49,  1.78it/s]

Checking batch → 83 origins × 12 destinations = 996 routes

Processing batches:   6%|▋         | 6/94 [00:04<00:43,  2.01it/s]

Checking batch → 61 origins × 27 destinations = 1647 routes

Processing batches:   7%|▋         | 7/94 [00:04<00:40,  2.14it/s]

Checking batch → 77 origins × 13 destinations = 1001 routes

Processing batches:   9%|▊         | 8/94 [00:04<00:37,  2.29it/s]

Checking batch → 125 origins × 17 destinations = 2125 routes

Processing batches:  10%|▉         | 9/94 [00:05<00:38,  2.23it/s]

Checking batch → 129 origins × 13 destinations = 1677 routes

Processing batches:  11%|█         | 10/94 [00:05<00:37,  2.25it/s]

Checking batch → 166 origins × 16 destinations = 2656 routes

Processing batches:  12%|█▏        | 11/94 [00:06<00:36,  2.26it/s]

Checking batch → 129 origins × 17 destinations = 2193 routes

Processing batches:  13%|█▎        | 12/94 [00:06<00:35,  2.29it/s]

Checking batch → 166 origins × 12 destinations = 1992 routes

Processing batches:  14%|█▍        | 13/94 [00:07<00:34,  2.32it/s]

Checking batch → 189 origins × 10 destinations = 1890 routes

Processing batches:  15%|█▍        | 14/94 [00:07<00:34,  2.30it/s]

Checking batch → 129 origins × 11 destinations = 1419 routes

Processing batches:  16%|█▌        | 15/94 [00:07<00:33,  2.33it/s]

Checking batch → 141 origins × 17 destinations = 2397 routes

Processing batches:  17%|█▋        | 16/94 [00:08<00:33,  2.36it/s]

Checking batch → 97 origins × 18 destinations = 1746 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  18%|█▊        | 17/94 [00:12<02:02,  1.59s/it]

Checking batch → 97 origins × 13 destinations = 1261 routes

Processing batches:  19%|█▉        | 18/94 [00:13<01:33,  1.23s/it]

Checking batch → 145 origins × 13 destinations = 1885 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  20%|██        | 19/94 [00:15<01:54,  1.53s/it]

Checking batch → 133 origins × 10 destinations = 1330 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  21%|██▏       | 20/94 [00:18<02:27,  1.99s/it]

Checking batch → 106 origins × 15 destinations = 1590 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  22%|██▏       | 21/94 [00:21<02:45,  2.27s/it]

Checking batch → 106 origins × 18 destinations = 1908 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  23%|██▎       | 22/94 [00:22<02:30,  2.09s/it]

Checking batch → 106 origins × 22 destinations = 2332 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  24%|██▍       | 23/94 [00:27<03:17,  2.78s/it]

Checking batch → 116 origins × 11 destinations = 1276 routes

Processing batches:  26%|██▌       | 24/94 [00:27<02:24,  2.06s/it]

Checking batch → 116 origins × 8 destinations = 928 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  27%|██▋       | 25/94 [00:29<02:14,  1.95s/it]

Checking batch → 80 origins × 16 destinations = 1280 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  28%|██▊       | 26/94 [00:33<03:06,  2.75s/it]

Checking batch → 129 origins × 11 destinations = 1419 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  29%|██▊       | 27/94 [01:18<17:01, 15.25s/it]

Checking batch → 291 origins × 5 destinations = 1455 routes

Processing batches:  30%|██▉       | 28/94 [01:19<11:59, 10.90s/it]

Checking batch → 291 origins × 5 destinations = 1455 routes

Processing batches:  31%|███       | 29/94 [01:19<08:31,  7.87s/it]

Checking batch → 291 origins × 5 destinations = 1455 routes

Processing batches:  32%|███▏      | 30/94 [01:20<06:01,  5.64s/it]

Checking batch → 166 origins × 9 destinations = 1494 routes

Processing batches:  33%|███▎      | 31/94 [01:20<04:16,  4.08s/it]

Checking batch → 239 origins × 6 destinations = 1434 routes

Processing batches:  34%|███▍      | 32/94 [01:21<03:05,  2.99s/it]

Checking batch → 71 origins × 17 destinations = 1207 routes

Processing batches:  35%|███▌      | 33/94 [01:21<02:14,  2.21s/it]

Checking batch → 116 origins × 22 destinations = 2552 routes

Processing batches:  36%|███▌      | 34/94 [01:22<01:40,  1.67s/it]

Checking batch → 129 origins × 14 destinations = 1806 routes

Processing batches:  37%|███▋      | 35/94 [01:22<01:16,  1.29s/it]

Checking batch → 85 origins × 16 destinations = 1360 routes

Processing batches:  38%|███▊      | 36/94 [01:22<00:59,  1.02s/it]

Checking batch → 60 origins × 19 destinations = 1140 routes

Processing batches:  39%|███▉      | 37/94 [01:23<00:47,  1.20it/s]

Checking batch → 83 origins × 17 destinations = 1411 routes

Processing batches:  40%|████      | 38/94 [01:23<00:39,  1.42it/s]

Checking batch → 77 origins × 17 destinations = 1309 routes

Processing batches:  41%|████▏     | 39/94 [01:24<00:33,  1.64it/s]

Checking batch → 89 origins × 13 destinations = 1157 routes

Processing batches:  43%|████▎     | 40/94 [01:24<00:29,  1.84it/s]

Checking batch → 90 origins × 16 destinations = 1440 routes

Processing batches:  44%|████▎     | 41/94 [01:24<00:26,  2.00it/s]

Checking batch → 129 origins × 17 destinations = 2193 routes

Processing batches:  45%|████▍     | 42/94 [01:25<00:24,  2.12it/s]

Checking batch → 233 origins × 9 destinations = 2097 routes

Processing batches:  46%|████▌     | 43/94 [01:25<00:23,  2.16it/s]

Checking batch → 116 origins × 11 destinations = 1276 routes

Processing batches:  47%|████▋     | 44/94 [01:26<00:21,  2.27it/s]

Checking batch → 132 origins × 11 destinations = 1452 routes

Processing batches:  48%|████▊     | 45/94 [01:26<00:20,  2.34it/s]

Checking batch → 61 origins × 19 destinations = 1159 routes

Processing batches:  49%|████▉     | 46/94 [01:26<00:19,  2.41it/s]

Checking batch → 94 origins × 14 destinations = 1316 routes

Processing batches:  50%|█████     | 47/94 [01:27<00:19,  2.46it/s]

Checking batch → 89 origins × 11 destinations = 979 routes

Processing batches:  51%|█████     | 48/94 [01:27<00:18,  2.44it/s]

Checking batch → 102 origins × 14 destinations = 1428 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  52%|█████▏    | 49/94 [01:32<01:16,  1.70s/it]

Checking batch → 114 origins × 13 destinations = 1482 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  53%|█████▎    | 50/94 [01:44<03:30,  4.78s/it]

Checking batch → 77 origins × 24 destinations = 1848 routes

Processing batches:  54%|█████▍    | 51/94 [01:44<02:28,  3.46s/it]

Checking batch → 68 origins × 27 destinations = 1836 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  55%|█████▌    | 52/94 [01:47<02:22,  3.39s/it]

Checking batch → 89 origins × 15 destinations = 1335 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  56%|█████▋    | 53/94 [02:27<09:43, 14.23s/it]

Checking batch → 106 origins × 17 destinations = 1802 routes

Processing batches:  57%|█████▋    | 54/94 [02:27<06:43, 10.09s/it]

Checking batch → 388 origins × 6 destinations = 2328 routes

Processing batches:  59%|█████▊    | 55/94 [02:28<04:44,  7.30s/it]

Checking batch → 355 origins × 6 destinations = 2130 routes

Processing batches:  60%|█████▉    | 56/94 [02:29<03:23,  5.35s/it]

Checking batch → 145 origins × 8 destinations = 1160 routes

Processing batches:  61%|██████    | 57/94 [02:29<02:23,  3.87s/it]

Checking batch → 130 origins × 11 destinations = 1430 routes

Processing batches:  62%|██████▏   | 58/94 [02:30<01:41,  2.83s/it]

Checking batch → 71 origins × 20 destinations = 1420 routes

Processing batches:  63%|██████▎   | 59/94 [02:30<01:13,  2.10s/it]

Checking batch → 55 origins × 37 destinations = 2035 routes

Processing batches:  64%|██████▍   | 60/94 [02:31<00:54,  1.59s/it]

Checking batch → 89 origins × 22 destinations = 1958 routes

Processing batches:  65%|██████▍   | 61/94 [02:36<01:31,  2.78s/it]

Checking batch → 129 origins × 12 destinations = 1548 routes

Processing batches:  66%|██████▌   | 62/94 [02:37<01:10,  2.21s/it]

Checking batch → 119 origins × 16 destinations = 1904 routes

Processing batches:  67%|██████▋   | 63/94 [02:38<00:54,  1.76s/it]

Checking batch → 388 origins × 4 destinations = 1552 routes

Processing batches:  68%|██████▊   | 64/94 [02:38<00:41,  1.37s/it]

Checking batch → 129 origins × 13 destinations = 1677 routes

Processing batches:  69%|██████▉   | 65/94 [02:39<00:31,  1.08s/it]

Checking batch → 79 origins × 15 destinations = 1185 routes

Processing batches:  70%|███████   | 66/94 [02:39<00:24,  1.15it/s]

Checking batch → 83 origins × 16 destinations = 1328 routes

Processing batches:  71%|███████▏  | 67/94 [02:39<00:19,  1.37it/s]

Checking batch → 97 origins × 13 destinations = 1261 routes

Processing batches:  72%|███████▏  | 68/94 [02:40<00:16,  1.61it/s]

Checking batch → 97 origins × 14 destinations = 1358 routes

Processing batches:  73%|███████▎  | 69/94 [02:40<00:14,  1.78it/s]

Checking batch → 116 origins × 15 destinations = 1740 routes

Processing batches:  74%|███████▍  | 70/94 [02:41<00:12,  1.94it/s]

Checking batch → 92 origins × 12 destinations = 1104 routes

Processing batches:  76%|███████▌  | 71/94 [02:41<00:11,  2.07it/s]

Checking batch → 190 origins × 10 destinations = 1900 routes

Processing batches:  77%|███████▋  | 72/94 [02:41<00:10,  2.14it/s]

Checking batch → 46 origins × 49 destinations = 2254 routes

Processing batches:  78%|███████▊  | 73/94 [02:42<00:10,  2.10it/s]

Checking batch → 55 origins × 31 destinations = 1705 routes

Processing batches:  79%|███████▊  | 74/94 [02:42<00:09,  2.19it/s]

Checking batch → 80 origins × 33 destinations = 2640 routes

Processing batches:  80%|███████▉  | 75/94 [02:43<00:10,  1.80it/s]

Checking batch → 100 origins × 24 destinations = 2400 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  81%|████████  | 76/94 [02:47<00:27,  1.53s/it]

Checking batch → 92 origins × 21 destinations = 1932 routes

Processing batches:  82%|████████▏ | 77/94 [02:47<00:20,  1.19s/it]

Checking batch → 53 origins × 38 destinations = 2014 routes

Processing batches:  83%|████████▎ | 78/94 [02:48<00:15,  1.04it/s]

Checking batch → 77 origins × 22 destinations = 1694 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  84%|████████▍ | 79/94 [03:43<04:17, 17.16s/it]

Checking batch → 72 origins × 28 destinations = 2016 routes

Processing batches:  85%|████████▌ | 80/94 [03:43<02:51, 12.22s/it]

Checking batch → 68 origins × 26 destinations = 1768 routes

Processing batches:  86%|████████▌ | 81/94 [03:44<01:52,  8.68s/it]

Checking batch → 149 origins × 14 destinations = 2086 routes

Processing batches:  87%|████████▋ | 82/94 [03:44<01:14,  6.21s/it]

Checking batch → 352 origins × 6 destinations = 2112 routes

Processing batches:  88%|████████▊ | 83/94 [03:45<00:50,  4.59s/it]

Checking batch → 145 origins × 19 destinations = 2755 routes

Processing batches:  89%|████████▉ | 84/94 [03:46<00:33,  3.35s/it]

Checking batch → 129 origins × 13 destinations = 1677 routes

Processing batches:  90%|█████████ | 85/94 [03:46<00:22,  2.47s/it]

Checking batch → 72 origins × 25 destinations = 1800 routes

Processing batches:  91%|█████████▏| 86/94 [03:46<00:14,  1.85s/it]

Checking batch → 92 origins × 24 destinations = 2208 routes

Processing batches:  93%|█████████▎| 87/94 [03:47<00:09,  1.42s/it]

Checking batch → 77 origins × 26 destinations = 2002 routes

Processing batches:  94%|█████████▎| 88/94 [03:47<00:06,  1.12s/it]

Checking batch → 63 origins × 26 destinations = 1638 routes

Processing batches:  95%|█████████▍| 89/94 [03:48<00:04,  1.12it/s]

Checking batch → 97 origins × 19 destinations = 1843 routes

Processing batches:  96%|█████████▌| 90/94 [03:48<00:02,  1.34it/s]

Checking batch → 233 origins × 10 destinations = 2330 routes

Processing batches:  97%|█████████▋| 91/94 [03:49<00:02,  1.50it/s]

Checking batch → 71 origins × 29 destinations = 2059 routes

Processing batches:  98%|█████████▊| 92/94 [03:49<00:01,  1.70it/s]

Checking batch → 49 origins × 37 destinations = 1813 routes

Processing batches:  99%|█████████▉| 93/94 [03:49<00:00,  1.86it/s]

Checking batch → 61 origins × 29 destinations = 1769 routes

Processing batches: 100%|██████████| 94/94 [03:50<00:00,  2.45s/it]

In [ ]:
# Save ORS distances for train stops into dataframe
df = pd.DataFrame({
    "rental_id": all_rental_ids,
    "top_distances": all_distances,
    "top_station_ids": all_station_ids
})

df.head()

   rental_id                   top_distances               top_station_ids
0   17694443    [3387.1, 22581.13, 22631.29]         [26199, 11219, 10117]
1   14799583  [20639.18, 20689.34, 21928.44]  [11219, 10117, vic:rail:JOR]
2   16807603  [19489.88, 19540.04, 20779.13]  [11219, 10117, vic:rail:JOR]
3   17744784    [20174.74, 20224.9, 21464.0]  [11219, 10117, vic:rail:JOR]
4   17745926  [18491.52, 18541.69, 19780.78]  [11219, 10117, vic:rail:JOR]

In [ ]:
# Call ORS to get distance to Melbourne CBD
melbourne_cbd = [144.96246406706035, -37.81227768714442]

max_route_per_batch = 3000

# Batch rentals for CBD calculation
batches = [rental_coords["listing_id"][i:i+max_route_per_batch]
           for i in range(0, len(rental_coords), max_route_per_batch)]

all_rental_ids = []
all_distance_to_cbd = []

for batch in tqdm(batches, desc="Calculating ORS distance to CBD in batches"):
    batch_coords = rental_coords.set_index("listing_id").loc[batch][["lon", "lat"]].values.tolist()

    num_origins = len(batch_coords)
    num_destinations = 1
    num_routes = num_origins * num_destinations
    print(f"Checking batch → {num_origins} origins × {num_destinations} destinations = {num_routes} routes")

    # Call ORS distance matrix
    matrix = client.distance_matrix(
        locations = batch_coords + [melbourne_cbd],
        profile = "driving-car",
        metrics = ["distance"],
        sources=list(range(len(batch_coords))),
        destinations=[len(batch_coords)]
    )

    # Extract distances for CBD 
    for i, rental_id in enumerate(batch):
        all_rental_ids.append(rental_id)
        all_distance_to_cbd.append(matrix["distances"][i][0])

Calculating ORS distance to CBD in batches:   0%|          | 0/4 [00:00<?, ?it/s]

Checking batch → 3000 origins × 1 destinations = 3000 routes

Calculating ORS distance to CBD in batches:  25%|██▌       | 1/4 [00:04<00:12,  4.05s/it]

Checking batch → 3000 origins × 1 destinations = 3000 routes

Calculating ORS distance to CBD in batches:  50%|█████     | 2/4 [00:05<00:04,  2.30s/it]

Checking batch → 3000 origins × 1 destinations = 3000 routes

Calculating ORS distance to CBD in batches:  75%|███████▌  | 3/4 [00:07<00:02,  2.13s/it]

Checking batch → 2618 origins × 1 destinations = 2618 routes

Calculating ORS distance to CBD in batches: 100%|██████████| 4/4 [00:08<00:00,  2.02s/it]

In [ ]:
# Save ORS distances for CBD to dataframe
df_cbd = pd.DataFrame({
    "rental_id": all_rental_ids,
    "distance_to_cbd": all_distance_to_cbd
})

df_cbd.head()

   rental_id  distance_to_cbd
0   16782629         10681.23
1   17471867         11022.42
2   17721851         11070.31
3   17725855         10739.04
4   17745057         10941.09

In [ ]:
# Combine train stop distances and CBD distances
combined_df = df.merge(
    df_cbd,
    on="rental_id",
    how="inner"
)

combined_df.head()

,rental_id,top_distances,top_station_ids,distance_to_cbd
0,17694443,"[3387.1, 22581.13, 22631.29]","[26199, 11219, 10117]",21520.46
1,14799583,"[20639.18, 20689.34, 21928.44]","[11219, 10117, vic:rail:JOR]",19578.50
2,16807603,"[19489.88, 19540.04, 20779.13]","[11219, 10117, vic:rail:JOR]",18429.20
3,17744784,"[20174.74, 20224.9, 21464.0]","[11219, 10117, vic:rail:JOR]",19114.06
4,17745926,"[18491.52, 18541.69, 19780.78]","[11219, 10117, vic:rail:JOR]",17430.85

In [ ]:
# Save final CSV
combined_df.to_csv("rentals_distances_to_train_stops_and_cbd.csv", index=False)