In [1]:
# Install openrouteservice for first time users
# !pip install openrouteservice

In [2]:
import openrouteservice
import pandas as pd
import numpy as np
from tqdm import tqdm

In [3]:
# Load in rental data
rental = pd.read_csv("rea_data/domain/Data/vic_rentals_all_cleaned.csv")
rental_coords = rental[["listing_id", "lon","lat"]]
rental_coords.head()

   listing_id        lon        lat
0    16782629  144.87091 -37.830982
1    17471867  144.86755 -37.826218
2    17721851  144.86632 -37.831226
3    17725855  144.86768 -37.827423
4    17745057  144.86790 -37.826270

In [4]:
# Load in bus stop data
bus = pd.read_csv("data\metro_bus_stops.txt")
bus_coords = bus[["stop_id", "stop_lon","stop_lat"]]
bus_coords.head()

  stop_id    stop_lon   stop_lat
0    1000  145.018951 -37.700775
1   10001  144.776152 -37.726975
2   10002  144.595789 -37.676159
3   10009  144.775899 -37.741497
4    1001  145.019685 -37.699183

In [5]:
# Define Haversine distance function
def haversine_vec(lon1, lat1, lon2, lat2):
    """
    Compute distance (meters) between two points using vectorised Haversine formula
    """
    lon1_rad = np.radians(lon1)[:, np.newaxis]
    lat1_rad = np.radians(lat1)[:, np.newaxis]

    lon2_rad = np.radians(lon2)[np.newaxis, :]
    lat2_rad = np.radians(lat2)[np.newaxis, :]

    earth_mean_radius = 6371000
    phi1, phi2 = lat1_rad, lat2_rad
    dphi1 = lat2_rad - lat1_rad
    dlambda = lon2_rad - lon1_rad
    
    a = np.sin(dphi1/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))

    return earth_mean_radius * c

In [6]:
# Find top 5 closest bus stops for each rental
dist_matrix = haversine_vec(rental_coords["lon"].values, rental_coords["lat"].values, bus_coords["stop_lon"].values, bus_coords["stop_lat"].values)

top5_indices = np.argsort(dist_matrix, axis=1)[:,:5]

rental_coords["top5_idx"] = list(top5_indices)
rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

C:\Users\chinj\AppData\Local\Temp\ipykernel_19532\1667537328.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_idx"] = list(top5_indices)
C:\Users\chinj\AppData\Local\Temp\ipykernel_19532\1667537328.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

In [7]:
# Group results by their top 5 closest bus stops
groups = rental_coords.groupby("top5_tuple")["listing_id"].apply(list).reset_index()
groups["num_rentals"] = groups["listing_id"].apply(len)

In [ ]:
# API key for OpenRouteService (ORS); hidden here for privacy
API_KEY = NA # Replace NA with your actual key when running

# Initialize ORS client with the API key
client = openrouteservice.Client(key = API_KEY)

In [9]:
# Batch rentals to stay under API route limit
top_n_bus = 5
max_route_per_batch = 3500

batches = []
current_batch = []
current_batch_rentals = 0

# Loop over each group of rentals that share the same top 5 bus stops
for _, row in groups.iterrows():
    group_name = row["top5_tuple"]
    rentals = row["listing_id"]
    group_size = len(rentals)

    start = 0
    # Split group into chunks so that adding them won't exceed ORS route limit
    while start < group_size:
        # Estimate number of rentals allowed to add to current batch without exceeding ORS route limit
        num_groups_if_added = len(current_batch) + 1
        max_rentals_for_this_chunk = max(
            (max_route_per_batch // (num_groups_if_added * top_n_bus)) - current_batch_rentals,
            1
        )

        # Determine slice of rentals for this chunk
        end = min(start + max_rentals_for_this_chunk, group_size)
        chunk = rentals[start:end]

        # Compute estimated number of routes if this chunk is added
        num_origins = current_batch_rentals + len(chunk)
        num_destinations = num_groups_if_added * top_n_bus
        estimated_routes = num_origins * num_destinations

        # Start new batch if adding this chunk exceeds ORS route limit
        if estimated_routes >= max_route_per_batch: 
            if current_batch:
                batches.append(current_batch)
            current_batch = [(group_name, chunk)]     
            current_batch_rentals = len(chunk)
        else:
            # Add chunk to batch otherwise
            current_batch.append((group_name, chunk))
            current_batch_rentals += len(chunk)
        start = end

# Append last batch if there are any remaining rentals
if current_batch:
        batches.append(current_batch)

print(f"Created {len(batches)} batches with full ORS route limit logic.")

Created 308 batches with full ORS route limit logic.

In [10]:
# Print and check summary of batches
for i, batch in enumerate(batches):
    num_groups = len(batch)
    num_rentals = sum(len(rentals) for _, rentals in batch)
    print(f"Batch {i+1}: {num_groups} groups, {num_rentals} rentals")

Batch 1: 25 groups, 26 rentals
Batch 2: 21 groups, 33 rentals
Batch 3: 19 groups, 32 rentals
Batch 4: 22 groups, 30 rentals
Batch 5: 22 groups, 30 rentals
Batch 6: 25 groups, 26 rentals
Batch 7: 24 groups, 28 rentals
Batch 8: 24 groups, 29 rentals
Batch 9: 21 groups, 31 rentals
Batch 10: 21 groups, 32 rentals
Batch 11: 21 groups, 32 rentals
Batch 12: 24 groups, 27 rentals
Batch 13: 23 groups, 29 rentals
Batch 14: 24 groups, 27 rentals
Batch 15: 20 groups, 33 rentals
Batch 16: 25 groups, 27 rentals
Batch 17: 21 groups, 33 rentals
Batch 18: 22 groups, 30 rentals
Batch 19: 22 groups, 30 rentals
Batch 20: 23 groups, 29 rentals
Batch 21: 25 groups, 27 rentals
Batch 22: 24 groups, 29 rentals
Batch 23: 21 groups, 31 rentals
Batch 24: 24 groups, 28 rentals
Batch 25: 24 groups, 29 rentals
Batch 26: 15 groups, 43 rentals
Batch 27: 23 groups, 29 rentals
Batch 28: 20 groups, 34 rentals
Batch 29: 23 groups, 30 rentals
Batch 30: 22 groups, 31 rentals
Batch 31: 19 groups, 34 rentals
Batch 32: 15 groups, 46 rentals
Batch 33: 15 groups, 45 rentals
Batch 34: 20 groups, 34 rentals
Batch 35: 17 groups, 40 rentals
Batch 36: 22 groups, 31 rentals
Batch 37: 18 groups, 38 rentals
Batch 38: 19 groups, 36 rentals
Batch 39: 17 groups, 38 rentals
Batch 40: 19 groups, 34 rentals
Batch 41: 22 groups, 30 rentals
Batch 42: 25 groups, 26 rentals
Batch 43: 22 groups, 31 rentals
Batch 44: 24 groups, 28 rentals
Batch 45: 21 groups, 33 rentals
Batch 46: 18 groups, 37 rentals
Batch 47: 22 groups, 30 rentals
Batch 48: 21 groups, 31 rentals
Batch 49: 24 groups, 28 rentals
Batch 50: 23 groups, 29 rentals
Batch 51: 24 groups, 27 rentals
Batch 52: 24 groups, 27 rentals
Batch 53: 23 groups, 29 rentals
Batch 54: 19 groups, 19 rentals
Batch 55: 2 groups, 243 rentals
Batch 56: 14 groups, 46 rentals
Batch 57: 24 groups, 29 rentals
Batch 58: 24 groups, 27 rentals
Batch 59: 24 groups, 27 rentals
Batch 60: 18 groups, 37 rentals
Batch 61: 21 groups, 31 rentals
Batch 62: 25 groups, 26 rentals
Batch 63: 21 groups, 33 rentals
Batch 64: 22 groups, 30 rentals
Batch 65: 24 groups, 27 rentals
Batch 66: 24 groups, 29 rentals
Batch 67: 24 groups, 27 rentals
Batch 68: 24 groups, 29 rentals
Batch 69: 24 groups, 27 rentals
Batch 70: 24 groups, 27 rentals
Batch 71: 25 groups, 27 rentals
Batch 72: 24 groups, 26 rentals
Batch 73: 20 groups, 33 rentals
Batch 74: 16 groups, 43 rentals
Batch 75: 15 groups, 43 rentals
Batch 76: 23 groups, 30 rentals
Batch 77: 15 groups, 46 rentals
Batch 78: 24 groups, 27 rentals
Batch 79: 19 groups, 36 rentals
Batch 80: 24 groups, 27 rentals
Batch 81: 24 groups, 27 rentals
Batch 82: 24 groups, 28 rentals
Batch 83: 17 groups, 41 rentals
Batch 84: 17 groups, 38 rentals
Batch 85: 19 groups, 35 rentals
Batch 86: 22 groups, 31 rentals
Batch 87: 24 groups, 28 rentals
Batch 88: 21 groups, 33 rentals
Batch 89: 24 groups, 29 rentals
Batch 90: 16 groups, 43 rentals
Batch 91: 24 groups, 27 rentals
Batch 92: 22 groups, 30 rentals
Batch 93: 25 groups, 27 rentals
Batch 94: 24 groups, 27 rentals
Batch 95: 26 groups, 26 rentals
Batch 96: 24 groups, 29 rentals
Batch 97: 25 groups, 27 rentals
Batch 98: 19 groups, 34 rentals
Batch 99: 21 groups, 33 rentals
Batch 100: 15 groups, 46 rentals
Batch 101: 25 groups, 27 rentals
Batch 102: 24 groups, 29 rentals
Batch 103: 24 groups, 27 rentals
Batch 104: 23 groups, 29 rentals
Batch 105: 24 groups, 29 rentals
Batch 106: 24 groups, 28 rentals
Batch 107: 18 groups, 38 rentals
Batch 108: 15 groups, 43 rentals
Batch 109: 24 groups, 27 rentals
Batch 110: 24 groups, 29 rentals
Batch 111: 25 groups, 27 rentals
Batch 112: 25 groups, 27 rentals
Batch 113: 22 groups, 30 rentals
Batch 114: 22 groups, 31 rentals
Batch 115: 21 groups, 31 rentals
Batch 116: 22 groups, 31 rentals
Batch 117: 19 groups, 35 rentals
Batch 118: 21 groups, 33 rentals
Batch 119: 19 groups, 33 rentals
Batch 120: 24 groups, 29 rentals
Batch 121: 25 groups, 27 rentals
Batch 122: 24 groups, 29 rentals
Batch 123: 25 groups, 27 rentals
Batch 124: 24 groups, 28 rentals
Batch 125: 25 groups, 27 rentals
Batch 126: 25 groups, 27 rentals
Batch 127: 24 groups, 27 rentals
Batch 128: 24 groups, 28 rentals
Batch 129: 23 groups, 29 rentals
Batch 130: 18 groups, 36 rentals
Batch 131: 22 groups, 30 rentals
Batch 132: 19 groups, 34 rentals
Batch 133: 11 groups, 63 rentals
Batch 134: 17 groups, 41 rentals
Batch 135: 22 groups, 30 rentals
Batch 136: 13 groups, 40 rentals
Batch 137: 12 groups, 58 rentals
Batch 138: 13 groups, 52 rentals
Batch 139: 14 groups, 46 rentals
Batch 140: 14 groups, 49 rentals
Batch 141: 17 groups, 38 rentals
Batch 142: 19 groups, 36 rentals
Batch 143: 8 groups, 83 rentals
Batch 144: 24 groups, 27 rentals
Batch 145: 22 groups, 31 rentals
Batch 146: 18 groups, 37 rentals
Batch 147: 14 groups, 49 rentals
Batch 148: 15 groups, 45 rentals
Batch 149: 23 groups, 30 rentals
Batch 150: 15 groups, 46 rentals
Batch 151: 9 groups, 77 rentals
Batch 152: 9 groups, 55 rentals
Batch 153: 16 groups, 42 rentals
Batch 154: 14 groups, 47 rentals
Batch 155: 24 groups, 28 rentals
Batch 156: 17 groups, 41 rentals
Batch 157: 8 groups, 77 rentals
Batch 158: 18 groups, 38 rentals
Batch 159: 24 groups, 29 rentals
Batch 160: 20 groups, 33 rentals
Batch 161: 23 groups, 30 rentals
Batch 162: 19 groups, 34 rentals
Batch 163: 22 groups, 30 rentals
Batch 164: 24 groups, 28 rentals
Batch 165: 9 groups, 77 rentals
Batch 166: 17 groups, 39 rentals
Batch 167: 23 groups, 30 rentals
Batch 168: 16 groups, 41 rentals
Batch 169: 24 groups, 27 rentals
Batch 170: 24 groups, 27 rentals
Batch 171: 17 groups, 40 rentals
Batch 172: 23 groups, 30 rentals
Batch 173: 23 groups, 29 rentals
Batch 174: 9 groups, 9 rentals
Batch 175: 3 groups, 233 rentals
Batch 176: 8 groups, 87 rentals
Batch 177: 19 groups, 36 rentals
Batch 178: 24 groups, 27 rentals
Batch 179: 24 groups, 28 rentals
Batch 180: 16 groups, 42 rentals
Batch 181: 23 groups, 30 rentals
Batch 182: 23 groups, 29 rentals
Batch 183: 24 groups, 29 rentals
Batch 184: 9 groups, 69 rentals
Batch 185: 6 groups, 111 rentals
Batch 186: 23 groups, 29 rentals
Batch 187: 18 groups, 38 rentals
Batch 188: 6 groups, 111 rentals
Batch 189: 24 groups, 27 rentals
Batch 190: 23 groups, 29 rentals
Batch 191: 24 groups, 29 rentals
Batch 192: 20 groups, 33 rentals
Batch 193: 19 groups, 23 rentals
Batch 194: 6 groups, 114 rentals
Batch 195: 16 groups, 41 rentals
Batch 196: 15 groups, 46 rentals
Batch 197: 14 groups, 48 rentals
Batch 198: 18 groups, 38 rentals
Batch 199: 15 groups, 46 rentals
Batch 200: 12 groups, 58 rentals
Batch 201: 6 groups, 108 rentals
Batch 202: 15 groups, 45 rentals
Batch 203: 17 groups, 39 rentals
Batch 204: 19 groups, 36 rentals
Batch 205: 19 groups, 30 rentals
Batch 206: 14 groups, 49 rentals
Batch 207: 16 groups, 41 rentals
Batch 208: 14 groups, 46 rentals
Batch 209: 16 groups, 41 rentals
Batch 210: 16 groups, 42 rentals
Batch 211: 17 groups, 38 rentals
Batch 212: 18 groups, 38 rentals
Batch 213: 23 groups, 30 rentals
Batch 214: 22 groups, 31 rentals
Batch 215: 18 groups, 38 rentals
Batch 216: 17 groups, 38 rentals
Batch 217: 22 groups, 30 rentals
Batch 218: 14 groups, 48 rentals
Batch 219: 10 groups, 69 rentals
Batch 220: 20 groups, 34 rentals
Batch 221: 20 groups, 33 rentals
Batch 222: 23 groups, 29 rentals
Batch 223: 24 groups, 28 rentals
Batch 224: 22 groups, 30 rentals
Batch 225: 24 groups, 27 rentals
Batch 226: 21 groups, 31 rentals
Batch 227: 17 groups, 39 rentals
Batch 228: 19 groups, 33 rentals
Batch 229: 12 groups, 54 rentals
Batch 230: 19 groups, 35 rentals
Batch 231: 21 groups, 32 rentals
Batch 232: 23 groups, 29 rentals
Batch 233: 17 groups, 39 rentals
Batch 234: 24 groups, 29 rentals
Batch 235: 19 groups, 36 rentals
Batch 236: 17 groups, 40 rentals
Batch 237: 17 groups, 38 rentals
Batch 238: 20 groups, 33 rentals
Batch 239: 24 groups, 28 rentals
Batch 240: 24 groups, 28 rentals
Batch 241: 11 groups, 61 rentals
Batch 242: 21 groups, 32 rentals
Batch 243: 20 groups, 34 rentals
Batch 244: 24 groups, 29 rentals
Batch 245: 25 groups, 26 rentals
Batch 246: 19 groups, 36 rentals
Batch 247: 4 groups, 161 rentals
Batch 248: 24 groups, 27 rentals
Batch 249: 22 groups, 31 rentals
Batch 250: 22 groups, 30 rentals
Batch 251: 25 groups, 27 rentals
Batch 252: 22 groups, 30 rentals
Batch 253: 23 groups, 30 rentals
Batch 254: 19 groups, 35 rentals
Batch 255: 20 groups, 33 rentals
Batch 256: 24 groups, 29 rentals
Batch 257: 19 groups, 34 rentals
Batch 258: 22 groups, 30 rentals
Batch 259: 24 groups, 28 rentals
Batch 260: 24 groups, 29 rentals
Batch 261: 23 groups, 30 rentals
Batch 262: 19 groups, 33 rentals
Batch 263: 15 groups, 46 rentals
Batch 264: 20 groups, 33 rentals
Batch 265: 18 groups, 38 rentals
Batch 266: 23 groups, 30 rentals
Batch 267: 21 groups, 31 rentals
Batch 268: 24 groups, 27 rentals
Batch 269: 19 groups, 35 rentals
Batch 270: 21 groups, 31 rentals
Batch 271: 19 groups, 35 rentals
Batch 272: 18 groups, 36 rentals
Batch 273: 15 groups, 46 rentals
Batch 274: 19 groups, 35 rentals
Batch 275: 22 groups, 30 rentals
Batch 276: 10 groups, 64 rentals
Batch 277: 5 groups, 137 rentals
Batch 278: 8 groups, 79 rentals
Batch 279: 21 groups, 33 rentals
Batch 280: 19 groups, 35 rentals
Batch 281: 24 groups, 29 rentals
Batch 282: 22 groups, 30 rentals
Batch 283: 23 groups, 30 rentals
Batch 284: 20 groups, 33 rentals
Batch 285: 14 groups, 47 rentals
Batch 286: 24 groups, 26 rentals
Batch 287: 25 groups, 27 rentals
Batch 288: 22 groups, 31 rentals
Batch 289: 21 groups, 32 rentals
Batch 290: 24 groups, 29 rentals
Batch 291: 21 groups, 33 rentals
Batch 292: 21 groups, 33 rentals
Batch 293: 14 groups, 49 rentals
Batch 294: 16 groups, 43 rentals
Batch 295: 17 groups, 41 rentals
Batch 296: 25 groups, 27 rentals
Batch 297: 24 groups, 29 rentals
Batch 298: 24 groups, 27 rentals
Batch 299: 19 groups, 36 rentals
Batch 300: 10 groups, 68 rentals
Batch 301: 22 groups, 30 rentals
Batch 302: 24 groups, 29 rentals
Batch 303: 22 groups, 30 rentals
Batch 304: 19 groups, 35 rentals
Batch 305: 20 groups, 34 rentals
Batch 306: 22 groups, 31 rentals
Batch 307: 20 groups, 34 rentals
Batch 308: 19 groups, 27 rentals

In [13]:
# Call ORS to get distance to closest bus stops
all_rental_ids = []
all_distances = []
all_bus_ids = []

for batch in tqdm(batches, desc="Processing batches"):
    batch_rentals = [r for _, rentals in batch for r in rentals]
    batch_coords = rental_coords.set_index("listing_id").loc[batch_rentals][["lon", "lat"]].values.tolist()

    batch_bus_indices = [
        rental_coords.loc[rental_coords["listing_id"]==r, "top5_idx"].values[0] for r in batch_rentals
    ]

    unique_bus_indices = list(set(idx for indices in batch_bus_indices for idx in indices))

    origins = batch_coords
    destinations = bus_coords.loc[bus_coords.index.isin(unique_bus_indices)][["stop_lon", "stop_lat"]].values.tolist()
    dest_ids_map = {idx: bus_coords["stop_id"].iloc[idx] for idx in unique_bus_indices}
   
    bus_pos_map = {idx: i for i, idx in enumerate(unique_bus_indices)}

    num_origins = len(origins)
    num_destinations = len(destinations)
    num_routes = num_origins * num_destinations
    print(f"Checking batch → {num_origins} origins × {num_destinations} destinations = {num_routes} routes")

    # Call ORS distance matrix
    matrix = client.distance_matrix(
        locations = origins + destinations,
        profile = "driving-car",
        metrics = ["distance"],
        sources = list(range(len(origins))),
        destinations = list(range(len(origins), len(origins)+len(destinations)))
    )

    # Extract distances and bus stop IDs for top 5 bus stops
    for i, rental in enumerate(batch_rentals):
        top_indices = batch_bus_indices[i]
        dest_positions = [bus_pos_map[idx] for idx in top_indices]
        rental_distances = [matrix["distances"][i][pos] for pos in dest_positions]
        rental_bus_ids = [dest_ids_map[idx] for idx in top_indices]

        cleaned_distances = [d if d is not None else float("inf") for d in rental_distances]

        sorted_idx = np.argsort(cleaned_distances)
        top_n_distances = [cleaned_distances[k] for k in sorted_idx]
        top_n_ids = [rental_bus_ids[k] for k in sorted_idx]

        all_rental_ids.append(batch_rentals[i])
        all_distances.append(top_n_distances)
        all_bus_ids.append(top_n_ids)

Processing batches:   0%|          | 0/308 [00:00<?, ?it/s]

Checking batch → 26 origins × 77 destinations = 2002 routes

Processing batches:   0%|          | 1/308 [00:02<15:14,  2.98s/it]

Checking batch → 33 origins × 62 destinations = 2046 routes

Processing batches:   1%|          | 2/308 [00:03<08:24,  1.65s/it]

Checking batch → 32 origins × 48 destinations = 1536 routes

Processing batches:   1%|          | 3/308 [00:04<05:46,  1.14s/it]

Checking batch → 30 origins × 61 destinations = 1830 routes

Processing batches:   1%|▏         | 4/308 [00:04<04:20,  1.17it/s]

Checking batch → 30 origins × 54 destinations = 1620 routes

Processing batches:   2%|▏         | 5/308 [00:05<03:32,  1.42it/s]

Checking batch → 26 origins × 80 destinations = 2080 routes

Processing batches:   2%|▏         | 6/308 [00:05<03:04,  1.64it/s]

Checking batch → 28 origins × 78 destinations = 2184 routes

Processing batches:   2%|▏         | 7/308 [00:06<03:07,  1.61it/s]

Checking batch → 29 origins × 94 destinations = 2726 routes

Processing batches:   3%|▎         | 8/308 [00:06<03:25,  1.46it/s]

Checking batch → 31 origins × 78 destinations = 2418 routes

Processing batches:   3%|▎         | 9/308 [00:07<03:00,  1.66it/s]

Checking batch → 32 origins × 80 destinations = 2560 routes

Processing batches:   3%|▎         | 10/308 [00:07<02:45,  1.80it/s]

Checking batch → 32 origins × 63 destinations = 2016 routes

Processing batches:   4%|▎         | 11/308 [00:08<02:32,  1.94it/s]

Checking batch → 27 origins × 85 destinations = 2295 routes

Processing batches:   4%|▍         | 12/308 [00:08<02:25,  2.04it/s]

Checking batch → 29 origins × 77 destinations = 2233 routes

Processing batches:   4%|▍         | 13/308 [00:09<02:18,  2.12it/s]

Checking batch → 27 origins × 67 destinations = 1809 routes

Processing batches:   5%|▍         | 14/308 [00:09<02:21,  2.07it/s]

Checking batch → 33 origins × 50 destinations = 1650 routes

Processing batches:   5%|▍         | 15/308 [00:10<02:15,  2.16it/s]

Checking batch → 27 origins × 79 destinations = 2133 routes

Processing batches:   5%|▌         | 16/308 [00:10<02:18,  2.11it/s]

Checking batch → 33 origins × 54 destinations = 1782 routes

Processing batches:   6%|▌         | 17/308 [00:10<02:13,  2.18it/s]

Checking batch → 30 origins × 52 destinations = 1560 routes

Processing batches:   6%|▌         | 18/308 [00:11<02:13,  2.18it/s]

Checking batch → 30 origins × 76 destinations = 2280 routes

Processing batches:   6%|▌         | 19/308 [00:11<02:11,  2.20it/s]

Checking batch → 29 origins × 78 destinations = 2262 routes

Processing batches:   6%|▋         | 20/308 [00:12<02:11,  2.18it/s]

Checking batch → 27 origins × 74 destinations = 1998 routes

Processing batches:   7%|▋         | 21/308 [00:12<02:09,  2.22it/s]

Checking batch → 29 origins × 68 destinations = 1972 routes

Processing batches:   7%|▋         | 22/308 [00:13<02:07,  2.24it/s]

Checking batch → 31 origins × 67 destinations = 2077 routes

Processing batches:   7%|▋         | 23/308 [00:13<02:05,  2.27it/s]

Checking batch → 28 origins × 55 destinations = 1540 routes

Processing batches:   8%|▊         | 24/308 [00:14<02:03,  2.30it/s]

Checking batch → 29 origins × 76 destinations = 2204 routes

Processing batches:   8%|▊         | 25/308 [00:14<02:01,  2.32it/s]

Checking batch → 43 origins × 40 destinations = 1720 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:   8%|▊         | 26/308 [00:16<04:03,  1.16it/s]

Checking batch → 29 origins × 91 destinations = 2639 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:   9%|▉         | 27/308 [01:12<1:21:03, 17.31s/it]

Checking batch → 34 origins × 65 destinations = 2210 routes

Processing batches:   9%|▉         | 28/308 [01:12<57:12, 12.26s/it]

Checking batch → 30 origins × 69 destinations = 2070 routes

Processing batches:   9%|▉         | 29/308 [01:13<40:37,  8.74s/it]

Checking batch → 31 origins × 69 destinations = 2139 routes

Processing batches:  10%|▉         | 30/308 [01:13<28:57,  6.25s/it]

Checking batch → 34 origins × 53 destinations = 1802 routes

Processing batches:  10%|█         | 31/308 [01:13<20:49,  4.51s/it]

Checking batch → 46 origins × 26 destinations = 1196 routes

Processing batches:  10%|█         | 32/308 [01:14<15:06,  3.29s/it]

Checking batch → 45 origins × 37 destinations = 1665 routes

Processing batches:  11%|█         | 33/308 [01:14<11:08,  2.43s/it]

Checking batch → 34 origins × 40 destinations = 1360 routes

Processing batches:  11%|█         | 34/308 [01:15<08:20,  1.83s/it]

Checking batch → 40 origins × 36 destinations = 1440 routes

Processing batches:  11%|█▏        | 35/308 [01:15<06:24,  1.41s/it]

Checking batch → 31 origins × 59 destinations = 1829 routes

Processing batches:  12%|█▏        | 36/308 [01:16<05:04,  1.12s/it]

Checking batch → 38 origins × 34 destinations = 1292 routes

Processing batches:  12%|█▏        | 37/308 [01:16<04:07,  1.10it/s]

Checking batch → 36 origins × 26 destinations = 936 routes

Processing batches:  12%|█▏        | 38/308 [01:17<03:40,  1.22it/s]

Checking batch → 38 origins × 37 destinations = 1406 routes

Processing batches:  13%|█▎        | 39/308 [01:17<03:10,  1.42it/s]

Checking batch → 34 origins × 47 destinations = 1598 routes

Processing batches:  13%|█▎        | 40/308 [01:18<02:49,  1.58it/s]

Checking batch → 30 origins × 59 destinations = 1770 routes

Processing batches:  13%|█▎        | 41/308 [01:18<02:40,  1.67it/s]

Checking batch → 26 origins × 56 destinations = 1456 routes

Processing batches:  14%|█▎        | 42/308 [01:18<02:26,  1.82it/s]

Checking batch → 31 origins × 66 destinations = 2046 routes

Processing batches:  14%|█▍        | 43/308 [01:19<02:16,  1.94it/s]

Checking batch → 28 origins × 101 destinations = 2828 routes

Processing batches:  14%|█▍        | 44/308 [01:19<02:20,  1.88it/s]

Checking batch → 33 origins × 64 destinations = 2112 routes

Processing batches:  15%|█▍        | 45/308 [01:20<02:11,  1.99it/s]

Checking batch → 37 origins × 33 destinations = 1221 routes

Processing batches:  15%|█▍        | 46/308 [01:20<02:10,  2.01it/s]

Checking batch → 30 origins × 44 destinations = 1320 routes

Processing batches:  15%|█▌        | 47/308 [01:21<02:04,  2.09it/s]

Checking batch → 31 origins × 53 destinations = 1643 routes

Processing batches:  16%|█▌        | 48/308 [01:21<01:59,  2.17it/s]

Checking batch → 28 origins × 76 destinations = 2128 routes

Processing batches:  16%|█▌        | 49/308 [01:22<02:16,  1.89it/s]

Checking batch → 29 origins × 77 destinations = 2233 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  16%|█▌        | 50/308 [01:24<04:29,  1.04s/it]

Checking batch → 27 origins × 83 destinations = 2241 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  17%|█▋        | 51/308 [01:32<12:36,  2.94s/it]

Checking batch → 27 origins × 88 destinations = 2376 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  17%|█▋        | 52/308 [01:34<11:24,  2.67s/it]

Checking batch → 29 origins × 74 destinations = 2146 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  17%|█▋        | 53/308 [02:17<1:02:39, 14.74s/it]

Checking batch → 19 origins × 73 destinations = 1387 routes

Processing batches:  18%|█▊        | 54/308 [02:17<44:20, 10.47s/it]

Checking batch → 243 origins × 5 destinations = 1215 routes

Processing batches:  18%|█▊        | 55/308 [02:18<32:05,  7.61s/it]

Checking batch → 46 origins × 40 destinations = 1840 routes

Processing batches:  18%|█▊        | 56/308 [02:18<22:56,  5.46s/it]

Checking batch → 29 origins × 78 destinations = 2262 routes

Processing batches:  19%|█▊        | 57/308 [02:19<16:33,  3.96s/it]

Checking batch → 27 origins × 91 destinations = 2457 routes

Processing batches:  19%|█▉        | 58/308 [02:19<12:06,  2.91s/it]

Checking batch → 27 origins × 94 destinations = 2538 routes

Processing batches:  19%|█▉        | 59/308 [02:20<08:58,  2.16s/it]

Checking batch → 37 origins × 52 destinations = 1924 routes

Processing batches:  19%|█▉        | 60/308 [02:20<06:58,  1.69s/it]

Checking batch → 31 origins × 58 destinations = 1798 routes

Processing batches:  20%|█▉        | 61/308 [02:21<05:35,  1.36s/it]

Checking batch → 26 origins × 97 destinations = 2522 routes

Processing batches:  20%|██        | 62/308 [02:21<04:26,  1.08s/it]

Checking batch → 33 origins × 77 destinations = 2541 routes

Processing batches:  20%|██        | 63/308 [02:22<03:57,  1.03it/s]

Checking batch → 30 origins × 52 destinations = 1560 routes

Processing batches:  21%|██        | 64/308 [02:22<03:15,  1.25it/s]

Checking batch → 27 origins × 89 destinations = 2403 routes

Processing batches:  21%|██        | 65/308 [02:23<02:47,  1.45it/s]

Checking batch → 29 origins × 89 destinations = 2581 routes

Processing batches:  21%|██▏       | 66/308 [02:23<02:40,  1.51it/s]

Checking batch → 27 origins × 68 destinations = 1836 routes

Processing batches:  22%|██▏       | 67/308 [02:24<02:28,  1.62it/s]

Checking batch → 29 origins × 66 destinations = 1914 routes

Processing batches:  22%|██▏       | 68/308 [02:25<02:35,  1.55it/s]

Checking batch → 27 origins × 69 destinations = 1863 routes

Processing batches:  22%|██▏       | 69/308 [02:25<02:24,  1.66it/s]

Checking batch → 27 origins × 49 destinations = 1323 routes

Processing batches:  23%|██▎       | 70/308 [02:26<02:11,  1.81it/s]

Checking batch → 27 origins × 85 destinations = 2295 routes

Processing batches:  23%|██▎       | 71/308 [02:26<02:01,  1.95it/s]

Checking batch → 26 origins × 82 destinations = 2132 routes

Processing batches:  23%|██▎       | 72/308 [02:27<01:56,  2.03it/s]

Checking batch → 33 origins × 59 destinations = 1947 routes

Processing batches:  24%|██▎       | 73/308 [02:27<01:53,  2.07it/s]

Checking batch → 43 origins × 57 destinations = 2451 routes

Processing batches:  24%|██▍       | 74/308 [02:27<01:49,  2.14it/s]

Checking batch → 43 origins × 49 destinations = 2107 routes

Processing batches:  24%|██▍       | 75/308 [02:28<01:56,  1.99it/s]

Checking batch → 30 origins × 83 destinations = 2490 routes

Processing batches:  25%|██▍       | 76/308 [02:28<01:51,  2.07it/s]

Checking batch → 46 origins × 38 destinations = 1748 routes

Processing batches:  25%|██▌       | 77/308 [02:29<01:50,  2.10it/s]

Checking batch → 27 origins × 76 destinations = 2052 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  25%|██▌       | 78/308 [02:31<03:53,  1.01s/it]

Checking batch → 36 origins × 71 destinations = 2556 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  26%|██▌       | 79/308 [03:28<1:07:54, 17.79s/it]

Checking batch → 27 origins × 66 destinations = 1782 routes

Processing batches:  26%|██▌       | 80/308 [03:29<47:47, 12.58s/it]

Checking batch → 27 origins × 74 destinations = 1998 routes

Processing batches:  26%|██▋       | 81/308 [03:29<33:47,  8.93s/it]

Checking batch → 28 origins × 62 destinations = 1736 routes

Processing batches:  27%|██▋       | 82/308 [03:29<24:02,  6.38s/it]

Checking batch → 41 origins × 18 destinations = 738 routes

Processing batches:  27%|██▋       | 83/308 [03:30<17:11,  4.58s/it]

Checking batch → 38 origins × 32 destinations = 1216 routes

Processing batches:  27%|██▋       | 84/308 [03:30<12:32,  3.36s/it]

Checking batch → 35 origins × 52 destinations = 1820 routes

Processing batches:  28%|██▊       | 85/308 [03:31<09:17,  2.50s/it]

Checking batch → 31 origins × 67 destinations = 2077 routes

Processing batches:  28%|██▊       | 86/308 [03:31<06:56,  1.88s/it]

Checking batch → 28 origins × 91 destinations = 2548 routes

Processing batches:  28%|██▊       | 87/308 [03:32<05:19,  1.44s/it]

Checking batch → 33 origins × 35 destinations = 1155 routes

Processing batches:  29%|██▊       | 88/308 [03:32<04:21,  1.19s/it]

Checking batch → 29 origins × 76 destinations = 2204 routes

Processing batches:  29%|██▉       | 89/308 [03:33<03:29,  1.05it/s]

Checking batch → 43 origins × 43 destinations = 1849 routes

Processing batches:  29%|██▉       | 90/308 [03:33<02:53,  1.26it/s]

Checking batch → 27 origins × 76 destinations = 2052 routes

Processing batches:  30%|██▉       | 91/308 [03:34<02:32,  1.42it/s]

Checking batch → 30 origins × 79 destinations = 2370 routes

Processing batches:  30%|██▉       | 92/308 [03:34<02:13,  1.61it/s]

Checking batch → 27 origins × 80 destinations = 2160 routes

Processing batches:  30%|███       | 93/308 [03:34<02:01,  1.77it/s]

Checking batch → 27 origins × 94 destinations = 2538 routes

Processing batches:  31%|███       | 94/308 [03:35<01:54,  1.87it/s]

Checking batch → 26 origins × 98 destinations = 2548 routes

Processing batches:  31%|███       | 95/308 [03:35<01:59,  1.78it/s]

Checking batch → 29 origins × 70 destinations = 2030 routes

Processing batches:  31%|███       | 96/308 [03:36<01:50,  1.92it/s]

Checking batch → 27 origins × 88 destinations = 2376 routes

Processing batches:  31%|███▏      | 97/308 [03:36<01:42,  2.05it/s]

Checking batch → 34 origins × 41 destinations = 1394 routes

Processing batches:  32%|███▏      | 98/308 [03:37<01:38,  2.14it/s]

Checking batch → 33 origins × 52 destinations = 1716 routes

Processing batches:  32%|███▏      | 99/308 [03:37<01:35,  2.18it/s]

Checking batch → 46 origins × 40 destinations = 1840 routes

Processing batches:  32%|███▏      | 100/308 [03:38<01:34,  2.21it/s]

Checking batch → 27 origins × 77 destinations = 2079 routes

Processing batches:  33%|███▎      | 101/308 [03:38<01:31,  2.26it/s]

Checking batch → 29 origins × 74 destinations = 2146 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  33%|███▎      | 102/308 [03:42<04:45,  1.39s/it]

Checking batch → 27 origins × 58 destinations = 1566 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  33%|███▎      | 103/308 [03:45<07:11,  2.11s/it]

Checking batch → 29 origins × 63 destinations = 1827 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  34%|███▍      | 104/308 [03:48<07:18,  2.15s/it]

Checking batch → 29 origins × 88 destinations = 2552 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  34%|███▍      | 105/308 [04:36<53:43, 15.88s/it]

Checking batch → 28 origins × 91 destinations = 2548 routes

Processing batches:  34%|███▍      | 106/308 [04:36<37:53, 11.26s/it]

Checking batch → 38 origins × 52 destinations = 1976 routes

Processing batches:  35%|███▍      | 107/308 [04:37<26:52,  8.02s/it]

Checking batch → 43 origins × 58 destinations = 2494 routes

Processing batches:  35%|███▌      | 108/308 [04:37<19:09,  5.75s/it]

Checking batch → 27 origins × 93 destinations = 2511 routes

Processing batches:  35%|███▌      | 109/308 [04:37<13:48,  4.17s/it]

Checking batch → 29 origins × 61 destinations = 1769 routes

Processing batches:  36%|███▌      | 110/308 [04:38<10:02,  3.04s/it]

Checking batch → 27 origins × 87 destinations = 2349 routes

Processing batches:  36%|███▌      | 111/308 [04:38<07:31,  2.29s/it]

Checking batch → 27 origins × 92 destinations = 2484 routes

Processing batches:  36%|███▋      | 112/308 [04:39<05:42,  1.75s/it]

Checking batch → 30 origins × 58 destinations = 1740 routes

Processing batches:  37%|███▋      | 113/308 [04:39<04:24,  1.35s/it]

Checking batch → 31 origins × 56 destinations = 1736 routes

Processing batches:  37%|███▋      | 114/308 [04:40<03:29,  1.08s/it]

Checking batch → 31 origins × 88 destinations = 2728 routes

Processing batches:  37%|███▋      | 115/308 [04:40<02:51,  1.12it/s]

Checking batch → 31 origins × 52 destinations = 1612 routes

Processing batches:  38%|███▊      | 116/308 [04:41<02:23,  1.33it/s]

Checking batch → 35 origins × 49 destinations = 1715 routes

Processing batches:  38%|███▊      | 117/308 [04:41<02:03,  1.54it/s]

Checking batch → 33 origins × 62 destinations = 2046 routes

Processing batches:  38%|███▊      | 118/308 [04:41<01:49,  1.74it/s]

Checking batch → 33 origins × 55 destinations = 1815 routes

Processing batches:  39%|███▊      | 119/308 [04:42<01:45,  1.80it/s]

Checking batch → 29 origins × 79 destinations = 2291 routes

Processing batches:  39%|███▉      | 120/308 [04:42<01:38,  1.91it/s]

Checking batch → 27 origins × 102 destinations = 2754 routes

Processing batches:  39%|███▉      | 121/308 [04:43<01:32,  2.02it/s]

Checking batch → 29 origins × 68 destinations = 1972 routes

Processing batches:  40%|███▉      | 122/308 [04:43<01:29,  2.09it/s]

Checking batch → 27 origins × 73 destinations = 1971 routes

Processing batches:  40%|███▉      | 123/308 [04:44<01:27,  2.11it/s]

Checking batch → 28 origins × 72 destinations = 2016 routes

Processing batches:  40%|████      | 124/308 [04:44<01:24,  2.18it/s]

Checking batch → 27 origins × 87 destinations = 2349 routes

Processing batches:  41%|████      | 125/308 [04:45<01:37,  1.88it/s]

Checking batch → 27 origins × 74 destinations = 1998 routes

Processing batches:  41%|████      | 126/308 [04:45<01:32,  1.96it/s]

Checking batch → 27 origins × 91 destinations = 2457 routes

Processing batches:  41%|████      | 127/308 [04:46<01:28,  2.04it/s]

Checking batch → 28 origins × 76 destinations = 2128 routes

Processing batches:  42%|████▏     | 128/308 [04:46<01:32,  1.95it/s]

Checking batch → 29 origins × 71 destinations = 2059 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  42%|████▏     | 129/308 [04:56<10:03,  3.37s/it]

Checking batch → 36 origins × 37 destinations = 1332 routes

Processing batches:  42%|████▏     | 130/308 [04:57<07:22,  2.49s/it]

Checking batch → 30 origins × 70 destinations = 2100 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  43%|████▎     | 131/308 [05:39<42:49, 14.52s/it]

Checking batch → 34 origins × 62 destinations = 2108 routes

Processing batches:  43%|████▎     | 132/308 [05:40<30:12, 10.30s/it]

Checking batch → 63 origins × 14 destinations = 882 routes

Processing batches:  43%|████▎     | 133/308 [05:40<21:22,  7.33s/it]

Checking batch → 41 origins × 27 destinations = 1107 routes

Processing batches:  44%|████▎     | 134/308 [05:41<15:18,  5.28s/it]

Checking batch → 30 origins × 80 destinations = 2400 routes

Processing batches:  44%|████▍     | 135/308 [05:41<11:05,  3.84s/it]

Checking batch → 40 origins × 34 destinations = 1360 routes

Processing batches:  44%|████▍     | 136/308 [05:42<08:07,  2.83s/it]

Checking batch → 58 origins × 17 destinations = 986 routes

Processing batches:  44%|████▍     | 137/308 [05:42<06:17,  2.21s/it]

Checking batch → 52 origins × 29 destinations = 1508 routes

Processing batches:  45%|████▍     | 138/308 [05:43<04:45,  1.68s/it]

Checking batch → 46 origins × 30 destinations = 1380 routes

Processing batches:  45%|████▌     | 139/308 [05:43<03:40,  1.30s/it]

Checking batch → 49 origins × 25 destinations = 1225 routes

Processing batches:  45%|████▌     | 140/308 [05:44<02:54,  1.04s/it]

Checking batch → 38 origins × 45 destinations = 1710 routes

Processing batches:  46%|████▌     | 141/308 [05:44<02:29,  1.12it/s]

Checking batch → 36 origins × 59 destinations = 2124 routes

Processing batches:  46%|████▌     | 142/308 [05:45<02:06,  1.32it/s]

Checking batch → 83 origins × 20 destinations = 1660 routes

Processing batches:  46%|████▋     | 143/308 [05:45<01:56,  1.42it/s]

Checking batch → 27 origins × 75 destinations = 2025 routes

Processing batches:  47%|████▋     | 144/308 [05:46<01:43,  1.58it/s]

Checking batch → 31 origins × 88 destinations = 2728 routes

Processing batches:  47%|████▋     | 145/308 [05:46<01:34,  1.72it/s]

Checking batch → 37 origins × 45 destinations = 1665 routes

Processing batches:  47%|████▋     | 146/308 [05:47<01:40,  1.61it/s]

Checking batch → 49 origins × 37 destinations = 1813 routes

Processing batches:  48%|████▊     | 147/308 [05:48<01:44,  1.54it/s]

Checking batch → 45 origins × 53 destinations = 2385 routes

Processing batches:  48%|████▊     | 148/308 [05:48<01:36,  1.66it/s]

Checking batch → 30 origins × 58 destinations = 1740 routes

Processing batches:  48%|████▊     | 149/308 [05:50<02:35,  1.02it/s]

Checking batch → 46 origins × 40 destinations = 1840 routes

Processing batches:  49%|████▊     | 150/308 [05:51<02:10,  1.21it/s]

Checking batch → 77 origins × 19 destinations = 1463 routes

Processing batches:  49%|████▉     | 151/308 [05:51<01:52,  1.40it/s]

Checking batch → 55 origins × 17 destinations = 935 routes

Processing batches:  49%|████▉     | 152/308 [05:52<01:46,  1.46it/s]

Checking batch → 42 origins × 45 destinations = 1890 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  50%|████▉     | 153/308 [05:54<03:12,  1.24s/it]

Checking batch → 47 origins × 30 destinations = 1410 routes

Processing batches:  50%|█████     | 154/308 [05:55<02:33,  1.00it/s]

Checking batch → 28 origins × 58 destinations = 1624 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  50%|█████     | 155/308 [05:56<03:11,  1.25s/it]

Checking batch → 41 origins × 25 destinations = 1025 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  51%|█████     | 156/308 [05:58<03:27,  1.37s/it]

Checking batch → 77 origins × 10 destinations = 770 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  51%|█████     | 157/308 [06:44<37:05, 14.74s/it]

Checking batch → 38 origins × 55 destinations = 2090 routes

Processing batches:  51%|█████▏    | 158/308 [06:45<26:30, 10.61s/it]

Checking batch → 29 origins × 94 destinations = 2726 routes

Processing batches:  52%|█████▏    | 159/308 [06:45<18:47,  7.57s/it]

Checking batch → 33 origins × 69 destinations = 2277 routes

Processing batches:  52%|█████▏    | 160/308 [06:46<13:23,  5.43s/it]

Checking batch → 30 origins × 71 destinations = 2130 routes

Processing batches:  52%|█████▏    | 161/308 [06:46<09:39,  3.94s/it]

Checking batch → 34 origins × 64 destinations = 2176 routes

Processing batches:  53%|█████▎    | 162/308 [06:47<07:12,  2.96s/it]

Checking batch → 30 origins × 74 destinations = 2220 routes

Processing batches:  53%|█████▎    | 163/308 [06:47<05:20,  2.21s/it]

Checking batch → 28 origins × 64 destinations = 1792 routes

Processing batches:  53%|█████▎    | 164/308 [06:48<04:01,  1.67s/it]

Checking batch → 77 origins × 20 destinations = 1540 routes

Processing batches:  54%|█████▎    | 165/308 [06:48<03:09,  1.32s/it]

Checking batch → 39 origins × 57 destinations = 2223 routes

Processing batches:  54%|█████▍    | 166/308 [06:49<02:39,  1.12s/it]

Checking batch → 30 origins × 62 destinations = 1860 routes

Processing batches:  54%|█████▍    | 167/308 [06:50<02:12,  1.06it/s]

Checking batch → 41 origins × 46 destinations = 1886 routes

Processing batches:  55%|█████▍    | 168/308 [06:50<01:50,  1.27it/s]

Checking batch → 27 origins × 57 destinations = 1539 routes

Processing batches:  55%|█████▍    | 169/308 [06:50<01:33,  1.48it/s]

Checking batch → 27 origins × 79 destinations = 2133 routes

Processing batches:  55%|█████▌    | 170/308 [06:51<01:29,  1.54it/s]

Checking batch → 40 origins × 42 destinations = 1680 routes

Processing batches:  56%|█████▌    | 171/308 [06:51<01:19,  1.72it/s]

Checking batch → 30 origins × 55 destinations = 1650 routes

Processing batches:  56%|█████▌    | 172/308 [06:52<01:23,  1.62it/s]

Checking batch → 29 origins × 69 destinations = 2001 routes

Processing batches:  56%|█████▌    | 173/308 [06:53<01:15,  1.78it/s]

Checking batch → 9 origins × 27 destinations = 243 routes

Processing batches:  56%|█████▋    | 174/308 [06:53<01:08,  1.97it/s]

Checking batch → 233 origins × 6 destinations = 1398 routes

Processing batches:  57%|█████▋    | 175/308 [06:53<01:08,  1.94it/s]

Checking batch → 87 origins × 16 destinations = 1392 routes

Processing batches:  57%|█████▋    | 176/308 [06:54<01:05,  2.02it/s]

Checking batch → 36 origins × 66 destinations = 2376 routes

Processing batches:  57%|█████▋    | 177/308 [06:54<01:02,  2.09it/s]

Checking batch → 27 origins × 83 destinations = 2241 routes

Processing batches:  58%|█████▊    | 178/308 [06:55<01:04,  2.02it/s]

Checking batch → 28 origins × 81 destinations = 2268 routes

Processing batches:  58%|█████▊    | 179/308 [06:55<01:01,  2.11it/s]

Checking batch → 42 origins × 44 destinations = 1848 routes

Processing batches:  58%|█████▊    | 180/308 [06:56<01:01,  2.08it/s]

Checking batch → 30 origins × 84 destinations = 2520 routes

Processing batches:  59%|█████▉    | 181/308 [06:56<01:00,  2.11it/s]

Checking batch → 29 origins × 78 destinations = 2262 routes

Processing batches:  59%|█████▉    | 182/308 [06:57<00:58,  2.15it/s]

Checking batch → 29 origins × 77 destinations = 2233 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  59%|█████▉    | 183/308 [07:54<36:24, 17.47s/it]

Checking batch → 69 origins × 21 destinations = 1449 routes

Processing batches:  60%|█████▉    | 184/308 [07:54<25:32, 12.36s/it]

Checking batch → 111 origins × 21 destinations = 2331 routes

Processing batches:  60%|██████    | 185/308 [07:55<18:06,  8.83s/it]

Checking batch → 29 origins × 77 destinations = 2233 routes

Processing batches:  60%|██████    | 186/308 [07:55<12:52,  6.34s/it]

Checking batch → 38 origins × 65 destinations = 2470 routes

Processing batches:  61%|██████    | 187/308 [07:56<09:13,  4.57s/it]

Checking batch → 111 origins × 17 destinations = 1887 routes

Processing batches:  61%|██████    | 188/308 [07:56<06:40,  3.34s/it]

Checking batch → 27 origins × 88 destinations = 2376 routes

Processing batches:  61%|██████▏   | 189/308 [07:57<04:56,  2.49s/it]

Checking batch → 29 origins × 79 destinations = 2291 routes

Processing batches:  62%|██████▏   | 190/308 [07:57<03:41,  1.88s/it]

Checking batch → 29 origins × 71 destinations = 2059 routes

Processing batches:  62%|██████▏   | 191/308 [07:58<02:48,  1.44s/it]

Checking batch → 33 origins × 64 destinations = 2112 routes

Processing batches:  62%|██████▏   | 192/308 [07:58<02:12,  1.14s/it]

Checking batch → 23 origins × 62 destinations = 1426 routes

Processing batches:  63%|██████▎   | 193/308 [07:59<01:46,  1.08it/s]

Checking batch → 114 origins × 15 destinations = 1710 routes

Processing batches:  63%|██████▎   | 194/308 [07:59<01:29,  1.27it/s]

Checking batch → 41 origins × 51 destinations = 2091 routes

Processing batches:  63%|██████▎   | 195/308 [07:59<01:16,  1.47it/s]

Checking batch → 46 origins × 40 destinations = 1840 routes

Processing batches:  64%|██████▎   | 196/308 [08:00<01:11,  1.56it/s]

Checking batch → 48 origins × 19 destinations = 912 routes

Processing batches:  64%|██████▍   | 197/308 [08:00<01:04,  1.72it/s]

Checking batch → 38 origins × 21 destinations = 798 routes

Processing batches:  64%|██████▍   | 198/308 [08:01<00:57,  1.91it/s]

Checking batch → 46 origins × 60 destinations = 2760 routes

Processing batches:  65%|██████▍   | 199/308 [08:01<00:54,  1.99it/s]

Checking batch → 58 origins × 23 destinations = 1334 routes

Processing batches:  65%|██████▍   | 200/308 [08:02<00:51,  2.09it/s]

Checking batch → 108 origins × 17 destinations = 1836 routes

Processing batches:  65%|██████▌   | 201/308 [08:02<00:53,  2.00it/s]

Checking batch → 45 origins × 40 destinations = 1800 routes

Processing batches:  66%|██████▌   | 202/308 [08:03<00:56,  1.87it/s]

Checking batch → 39 origins × 32 destinations = 1248 routes

Processing batches:  66%|██████▌   | 203/308 [08:03<00:53,  1.95it/s]

Checking batch → 36 origins × 26 destinations = 936 routes

Processing batches:  66%|██████▌   | 204/308 [08:04<00:49,  2.09it/s]

Checking batch → 30 origins × 27 destinations = 810 routes

Processing batches:  67%|██████▋   | 205/308 [08:04<00:47,  2.18it/s]

Checking batch → 49 origins × 21 destinations = 1029 routes

Processing batches:  67%|██████▋   | 206/308 [08:05<00:45,  2.26it/s]

Checking batch → 41 origins × 19 destinations = 779 routes

Processing batches:  67%|██████▋   | 207/308 [08:05<00:43,  2.33it/s]

Checking batch → 46 origins × 18 destinations = 828 routes

Processing batches:  68%|██████▊   | 208/308 [08:05<00:41,  2.38it/s]

Checking batch → 41 origins × 36 destinations = 1476 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  68%|██████▊   | 209/308 [08:57<26:16, 15.92s/it]

Checking batch → 42 origins × 25 destinations = 1050 routes

Processing batches:  68%|██████▊   | 210/308 [08:58<18:24, 11.27s/it]

Checking batch → 38 origins × 40 destinations = 1520 routes

Processing batches:  69%|██████▊   | 211/308 [08:58<12:58,  8.03s/it]

Checking batch → 38 origins × 39 destinations = 1482 routes

Processing batches:  69%|██████▉   | 212/308 [08:59<09:12,  5.76s/it]

Checking batch → 30 origins × 63 destinations = 1890 routes

Processing batches:  69%|██████▉   | 213/308 [08:59<06:35,  4.16s/it]

Checking batch → 31 origins × 57 destinations = 1767 routes

Processing batches:  69%|██████▉   | 214/308 [09:00<04:45,  3.03s/it]

Checking batch → 38 origins × 43 destinations = 1634 routes

Processing batches:  70%|██████▉   | 215/308 [09:00<03:31,  2.27s/it]

Checking batch → 38 origins × 39 destinations = 1482 routes

Processing batches:  70%|███████   | 216/308 [09:01<02:40,  1.75s/it]

Checking batch → 30 origins × 69 destinations = 2070 routes

Processing batches:  70%|███████   | 217/308 [09:01<02:02,  1.35s/it]

Checking batch → 48 origins × 32 destinations = 1536 routes

Processing batches:  71%|███████   | 218/308 [09:01<01:36,  1.07s/it]

Checking batch → 69 origins × 19 destinations = 1311 routes

Processing batches:  71%|███████   | 219/308 [09:02<01:18,  1.13it/s]

Checking batch → 34 origins × 58 destinations = 1972 routes

Processing batches:  71%|███████▏  | 220/308 [09:02<01:09,  1.27it/s]

Checking batch → 33 origins × 49 destinations = 1617 routes

Processing batches:  72%|███████▏  | 221/308 [09:03<01:08,  1.26it/s]

Checking batch → 29 origins × 53 destinations = 1537 routes

Processing batches:  72%|███████▏  | 222/308 [09:04<00:58,  1.47it/s]

Checking batch → 28 origins × 54 destinations = 1512 routes

Processing batches:  72%|███████▏  | 223/308 [09:04<00:51,  1.66it/s]

Checking batch → 30 origins × 71 destinations = 2130 routes

Processing batches:  73%|███████▎  | 224/308 [09:05<00:45,  1.83it/s]

Checking batch → 27 origins × 66 destinations = 1782 routes

Processing batches:  73%|███████▎  | 225/308 [09:05<00:42,  1.97it/s]

Checking batch → 31 origins × 78 destinations = 2418 routes

Processing batches:  73%|███████▎  | 226/308 [09:05<00:40,  2.04it/s]

Checking batch → 39 origins × 55 destinations = 2145 routes

Processing batches:  74%|███████▎  | 227/308 [09:06<00:40,  1.98it/s]

Checking batch → 33 origins × 53 destinations = 1749 routes

Processing batches:  74%|███████▍  | 228/308 [09:06<00:38,  2.08it/s]

Checking batch → 54 origins × 36 destinations = 1944 routes

Processing batches:  74%|███████▍  | 229/308 [09:07<00:38,  2.06it/s]

Checking batch → 35 origins × 55 destinations = 1925 routes

Processing batches:  75%|███████▍  | 230/308 [09:07<00:36,  2.11it/s]

Checking batch → 32 origins × 52 destinations = 1664 routes

Processing batches:  75%|███████▌  | 231/308 [09:08<00:38,  1.98it/s]

Checking batch → 29 origins × 73 destinations = 2117 routes

Processing batches:  75%|███████▌  | 232/308 [09:09<00:45,  1.67it/s]

Checking batch → 39 origins × 71 destinations = 2769 routes

Processing batches:  76%|███████▌  | 233/308 [09:09<00:41,  1.80it/s]

Checking batch → 29 origins × 70 destinations = 2030 routes

Processing batches:  76%|███████▌  | 234/308 [09:10<00:38,  1.92it/s]

Checking batch → 36 origins × 40 destinations = 1440 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  76%|███████▋  | 235/308 [10:02<19:44, 16.23s/it]

Checking batch → 40 origins × 29 destinations = 1160 routes

Processing batches:  77%|███████▋  | 236/308 [10:03<13:47, 11.49s/it]

Checking batch → 38 origins × 36 destinations = 1368 routes

Processing batches:  77%|███████▋  | 237/308 [10:03<09:40,  8.17s/it]

Checking batch → 33 origins × 71 destinations = 2343 routes

Processing batches:  77%|███████▋  | 238/308 [10:04<06:50,  5.86s/it]

Checking batch → 28 origins × 69 destinations = 1932 routes

Processing batches:  78%|███████▊  | 239/308 [10:04<04:52,  4.24s/it]

Checking batch → 28 origins × 68 destinations = 1904 routes

Processing batches:  78%|███████▊  | 240/308 [10:05<03:30,  3.10s/it]

Checking batch → 61 origins × 27 destinations = 1647 routes

Processing batches:  78%|███████▊  | 241/308 [10:05<02:34,  2.31s/it]

Checking batch → 32 origins × 68 destinations = 2176 routes

Processing batches:  79%|███████▊  | 242/308 [10:06<01:58,  1.79s/it]

Checking batch → 34 origins × 78 destinations = 2652 routes

Processing batches:  79%|███████▉  | 243/308 [10:06<01:31,  1.41s/it]

Checking batch → 29 origins × 76 destinations = 2204 routes

Processing batches:  79%|███████▉  | 244/308 [10:07<01:13,  1.14s/it]

Checking batch → 26 origins × 87 destinations = 2262 routes

Processing batches:  80%|███████▉  | 245/308 [10:07<00:59,  1.07it/s]

Checking batch → 36 origins × 66 destinations = 2376 routes

Processing batches:  80%|███████▉  | 246/308 [10:08<00:51,  1.20it/s]

Checking batch → 161 origins × 11 destinations = 1771 routes

Processing batches:  80%|████████  | 247/308 [10:09<00:48,  1.25it/s]

Checking batch → 27 origins × 80 destinations = 2160 routes

Processing batches:  81%|████████  | 248/308 [10:09<00:42,  1.43it/s]

Checking batch → 31 origins × 79 destinations = 2449 routes

Processing batches:  81%|████████  | 249/308 [10:09<00:36,  1.61it/s]

Checking batch → 30 origins × 65 destinations = 1950 routes

Processing batches:  81%|████████  | 250/308 [10:10<00:32,  1.77it/s]

Checking batch → 27 origins × 110 destinations = 2970 routes

Processing batches:  81%|████████▏ | 251/308 [10:10<00:31,  1.82it/s]

Checking batch → 30 origins × 63 destinations = 1890 routes

Processing batches:  82%|████████▏ | 252/308 [10:11<00:31,  1.79it/s]

Checking batch → 30 origins × 45 destinations = 1350 routes

Processing batches:  82%|████████▏ | 253/308 [10:11<00:28,  1.91it/s]

Checking batch → 35 origins × 52 destinations = 1820 routes

Processing batches:  82%|████████▏ | 254/308 [10:12<00:27,  1.98it/s]

Checking batch → 33 origins × 75 destinations = 2475 routes

Processing batches:  83%|████████▎ | 255/308 [10:12<00:27,  1.92it/s]

Checking batch → 29 origins × 67 destinations = 1943 routes

Processing batches:  83%|████████▎ | 256/308 [10:13<00:26,  1.94it/s]

Checking batch → 34 origins × 69 destinations = 2346 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  83%|████████▎ | 257/308 [10:18<01:36,  1.89s/it]

Checking batch → 30 origins × 70 destinations = 2100 routes

Processing batches:  84%|████████▍ | 258/308 [10:19<01:13,  1.47s/it]

Checking batch → 28 origins × 72 destinations = 2016 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  84%|████████▍ | 259/308 [10:23<01:54,  2.33s/it]

Checking batch → 29 origins × 79 destinations = 2291 routes

Processing batches:  84%|████████▍ | 260/308 [10:23<01:26,  1.81s/it]

Checking batch → 30 origins × 74 destinations = 2220 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  85%|████████▍ | 261/308 [11:17<13:34, 17.33s/it]

Checking batch → 33 origins × 21 destinations = 693 routes

Processing batches:  85%|████████▌ | 262/308 [11:18<09:25, 12.28s/it]

Checking batch → 46 origins × 29 destinations = 1334 routes

Processing batches:  85%|████████▌ | 263/308 [11:18<06:32,  8.73s/it]

Checking batch → 33 origins × 50 destinations = 1650 routes

Processing batches:  86%|████████▌ | 264/308 [11:18<04:35,  6.26s/it]

Checking batch → 38 origins × 45 destinations = 1710 routes

Processing batches:  86%|████████▌ | 265/308 [11:19<03:14,  4.53s/it]

Checking batch → 30 origins × 66 destinations = 1980 routes

Processing batches:  86%|████████▋ | 266/308 [11:19<02:19,  3.33s/it]

Checking batch → 31 origins × 68 destinations = 2108 routes

Processing batches:  87%|████████▋ | 267/308 [11:20<01:40,  2.46s/it]

Checking batch → 27 origins × 82 destinations = 2214 routes

Processing batches:  87%|████████▋ | 268/308 [11:20<01:14,  1.87s/it]

Checking batch → 35 origins × 57 destinations = 1995 routes

Processing batches:  87%|████████▋ | 269/308 [11:21<00:57,  1.46s/it]

Checking batch → 31 origins × 69 destinations = 2139 routes

Processing batches:  88%|████████▊ | 270/308 [11:23<00:59,  1.57s/it]

Checking batch → 35 origins × 52 destinations = 1820 routes

Processing batches:  88%|████████▊ | 271/308 [11:23<00:45,  1.23s/it]

Checking batch → 36 origins × 44 destinations = 1584 routes

Processing batches:  88%|████████▊ | 272/308 [11:24<00:35,  1.01it/s]

Checking batch → 46 origins × 52 destinations = 2392 routes

Processing batches:  89%|████████▊ | 273/308 [11:24<00:28,  1.21it/s]

Checking batch → 35 origins × 37 destinations = 1295 routes

Processing batches:  89%|████████▉ | 274/308 [11:25<00:25,  1.34it/s]

Checking batch → 30 origins × 61 destinations = 1830 routes

Processing batches:  89%|████████▉ | 275/308 [11:25<00:21,  1.54it/s]

Checking batch → 64 origins × 27 destinations = 1728 routes

Processing batches:  90%|████████▉ | 276/308 [11:26<00:19,  1.66it/s]

Checking batch → 137 origins × 9 destinations = 1233 routes

Processing batches:  90%|████████▉ | 277/308 [11:26<00:19,  1.57it/s]

Checking batch → 79 origins × 26 destinations = 2054 routes

Processing batches:  90%|█████████ | 278/308 [11:27<00:20,  1.45it/s]

Checking batch → 33 origins × 58 destinations = 1914 routes

Processing batches:  91%|█████████ | 279/308 [11:28<00:18,  1.57it/s]

Checking batch → 35 origins × 69 destinations = 2415 routes

Processing batches:  91%|█████████ | 280/308 [11:28<00:16,  1.73it/s]

Checking batch → 29 origins × 68 destinations = 1972 routes

Processing batches:  91%|█████████ | 281/308 [11:28<00:14,  1.89it/s]

Checking batch → 30 origins × 65 destinations = 1950 routes

Processing batches:  92%|█████████▏| 282/308 [11:29<00:12,  2.01it/s]

Checking batch → 30 origins × 75 destinations = 2250 routes

Processing batches:  92%|█████████▏| 283/308 [11:29<00:12,  2.08it/s]

Checking batch → 33 origins × 70 destinations = 2310 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  92%|█████████▏| 284/308 [11:33<00:33,  1.39s/it]

Checking batch → 47 origins × 35 destinations = 1645 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  93%|█████████▎| 285/308 [11:35<00:35,  1.55s/it]

Checking batch → 26 origins × 72 destinations = 1872 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  93%|█████████▎| 286/308 [11:37<00:38,  1.76s/it]

Checking batch → 27 origins × 82 destinations = 2214 routes

c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 7th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
c:\Users\chinj\anaconda3\Lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 8th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
Processing batches:  93%|█████████▎| 287/308 [12:28<05:49, 16.63s/it]

Checking batch → 31 origins × 67 destinations = 2077 routes

Processing batches:  94%|█████████▎| 288/308 [12:29<03:55, 11.77s/it]

Checking batch → 32 origins × 62 destinations = 1984 routes

Processing batches:  94%|█████████▍| 289/308 [12:29<02:39,  8.38s/it]

Checking batch → 29 origins × 78 destinations = 2262 routes

Processing batches:  94%|█████████▍| 290/308 [12:30<01:48,  6.03s/it]

Checking batch → 33 origins × 60 destinations = 1980 routes

Processing batches:  94%|█████████▍| 291/308 [12:30<01:13,  4.35s/it]

Checking batch → 33 origins × 61 destinations = 2013 routes

Processing batches:  95%|█████████▍| 292/308 [12:31<00:50,  3.18s/it]

Checking batch → 49 origins × 26 destinations = 1274 routes

Processing batches:  95%|█████████▌| 293/308 [12:31<00:35,  2.39s/it]

Checking batch → 43 origins × 17 destinations = 731 routes

Processing batches:  95%|█████████▌| 294/308 [12:32<00:25,  1.82s/it]

Checking batch → 41 origins × 40 destinations = 1640 routes

Processing batches:  96%|█████████▌| 295/308 [12:32<00:18,  1.41s/it]

Checking batch → 27 origins × 76 destinations = 2052 routes

Processing batches:  96%|█████████▌| 296/308 [12:33<00:13,  1.11s/it]

Checking batch → 29 origins × 100 destinations = 2900 routes

Processing batches:  96%|█████████▋| 297/308 [12:33<00:10,  1.10it/s]

Checking batch → 27 origins × 70 destinations = 1890 routes

Processing batches:  97%|█████████▋| 298/308 [12:33<00:07,  1.30it/s]

Checking batch → 36 origins × 65 destinations = 2340 routes

Processing batches:  97%|█████████▋| 299/308 [12:34<00:06,  1.49it/s]

Checking batch → 68 origins × 23 destinations = 1564 routes

Processing batches:  97%|█████████▋| 300/308 [12:34<00:04,  1.63it/s]

Checking batch → 30 origins × 62 destinations = 1860 routes

Processing batches:  98%|█████████▊| 301/308 [12:35<00:04,  1.71it/s]

Checking batch → 29 origins × 94 destinations = 2726 routes

Processing batches:  98%|█████████▊| 302/308 [12:35<00:03,  1.84it/s]

Checking batch → 30 origins × 67 destinations = 2010 routes

Processing batches:  98%|█████████▊| 303/308 [12:36<00:02,  1.95it/s]

Checking batch → 35 origins × 73 destinations = 2555 routes

Processing batches:  99%|█████████▊| 304/308 [12:36<00:02,  1.81it/s]

Checking batch → 34 origins × 51 destinations = 1734 routes

Processing batches:  99%|█████████▉| 305/308 [12:37<00:01,  1.94it/s]

Checking batch → 31 origins × 79 destinations = 2449 routes

Processing batches:  99%|█████████▉| 306/308 [12:37<00:00,  2.04it/s]

Checking batch → 34 origins × 47 destinations = 1598 routes

Processing batches: 100%|█████████▉| 307/308 [12:38<00:00,  2.14it/s]

Checking batch → 27 origins × 70 destinations = 1890 routes

Processing batches: 100%|██████████| 308/308 [12:38<00:00,  2.46s/it]

In [14]:
# Save ORS distances for bus stops into dataframe
df = pd.DataFrame({
    "rental_id": all_rental_ids,
    "top_distances": all_distances,
    "top_bus_ids": all_bus_ids
})

df.head()

,rental_id,top_distances,top_bus_ids
0,17747586,"[433.52, 581.43, 14211.31, 25808.42, 55651.27]","[1001, 1000, 10345, 1201, 10837]"
1,17292142,"[440.8, 536.4, 960.47, 26116.62, 26390.48]","[1000, 1001, 1202, 1201, 1200]"
2,17717715,"[671.15, 2716.4, 25618.05, 26167.44, 53286.2]","[1000, 998, 1199, 999, 1198]"
3,17721816,"[765.37, 26715.05, 27772.45, 27990.99, 29923.31]","[1000, 1200, 22361, 999, 22359]"
4,16512589,"[803.2, 21361.67, 21659.3, 28089.64, 28258.79]","[10001, 22678, 22674, 10308, 10307]"

In [15]:
# Save final CSV
df.to_csv("rentals_distances_to_bus_stops.csv", index=False)